import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowRight, Cloud, Database, GitBranch, Network, Server, ShieldCheck, Users } from "lucide-react";

export const Route = createFileRoute("/autonomous-testing")({
  head: () => ({ meta: [
    { title: "Make Testing Self-Driving | Shyena" },
    { name: "description", content: "Make testing self-driving. Shyena agents automate testing through your existing infrastructure so testers can focus on risk, quality and release decisions." },
    { property: "og:title", content: "Make testing self-driving. Make testers more strategic. | Shyena" },
    { property: "og:description", content: "Shyena agents take care of automation work through your existing testing infrastructure, while testers focus on risk, quality and release decisions." },
  ]}),
  component: AutonomousTestingPage,
});

const agents = [
  ["01", "KNOW", "Understand change, system, requirements and existing coverage."],
  ["02", "DECIDE", "Assess impact, risk and what actually needs to be tested."],
  ["03", "ORCHESTRATE", "Generate and coordinate testing through your existing stack."],
  ["04", "INVESTIGATE", "Analyse failures, distinguish defects and adapt safely."],
  ["05", "PROVE", "Correlate evidence and make the release decision actionable."],
] as const;
const infra = [
  ["UI & mobile", "Playwright · Selenium · Cypress · Appium", Network],
  ["API & contract", "Service and contract testing", Server],
  ["CI/CD", "Your existing delivery pipelines", GitBranch],
  ["Cloud & environments", "Your cloud, VPC and test environments", Cloud],
  ["Test data", "Your databases, fixtures and test data", Database],
  ["Observability", "Your logs, traces and runtime signals", ShieldCheck],
] as const;
const shifts = [
  ["Write automation", "Agents generate automation from test intent"],
  ["Maintain scripts", "Agents investigate and safely repair automation issues"],
  ["Run regression", "Agents select and orchestrate what matters"],
  ["Analyse failures", "Agents correlate browser, API, data and observability evidence"],
  ["Report results", "Agents build traceable assurance evidence"],
  ["Execute tests", "Testers focus on risk, quality and release decisions"],
] as const;

function Connector() { return <div className="relative h-9 w-px bg-slate-300"><span className="absolute -left-[3px] top-0 h-2 w-2 rounded-full bg-[#ffb703]" /></div>; }

function Flow() {
  return <div className="overflow-hidden border border-slate-300 bg-white shadow-[0_35px_90px_-55px_rgba(15,23,42,.5)]">
    <div className="flex items-center justify-between border-b border-slate-300 bg-[#0b0920] px-5 py-4 text-white"><div className="font-mono text-[9px] font-bold uppercase tracking-[.18em] text-[#ffb703]">From change to confidence</div><div className="hidden font-mono text-[9px] uppercase tracking-[.16em] text-white/35 sm:block">Self-driving quality flow</div></div>
    <div className="bg-[#f8fafc] p-4 sm:p-7 lg:p-9"><div className="mx-auto flex max-w-6xl flex-col items-center">
      <div className="w-full border border-slate-300 bg-white p-5 sm:p-6"><div className="font-mono text-[9px] font-bold uppercase tracking-[.18em] text-slate-400">01 · Your change</div><div className="mt-3 flex flex-wrap gap-2">{["Requirements / Jira","Git / code","CI/CD","Docs / rules"].map(x=><div key={x} className="border border-slate-200 bg-[#f8fafc] px-4 py-3 text-[10px] font-bold">{x}</div>)}</div></div>
      <Connector />
      <div className="w-full border-2 border-slate-900 bg-[#0b0920] p-5 text-white sm:p-7"><div className="mb-5"><div className="font-mono text-[9px] font-bold uppercase tracking-[.18em] text-[#ffb703]">02 · Shyena agents</div><div className="mt-2 font-[Sora] text-xl font-extrabold">The testing intelligence</div><div className="mt-1 max-w-3xl text-[10px] leading-5 text-white/45">Agents autonomously drive the testing lifecycle. Humans remain accountable for quality and release decisions.</div></div><div className="grid gap-2 sm:grid-cols-5">{agents.map(([n,t,d])=><div key={t} className="border border-white/10 bg-white/[.045] p-4"><div className="font-mono text-[8px] font-bold text-[#ffb703]">{n}</div><div className="mt-2 text-[10px] font-extrabold">{t}</div><div className="mt-2 text-[8px] leading-4 text-white/40">{d}</div></div>)}</div></div>
      <Connector />
      <div className="w-full border border-[#ffb703] bg-white p-5 sm:p-7"><div className="text-center"><div className="font-mono text-[9px] font-bold uppercase tracking-[.18em] text-slate-400">03 · Your existing infrastructure</div><div className="mt-2 font-[Sora] text-xl font-extrabold tracking-[-.025em]">Keep your testing stack. Add autonomous intelligence.</div><div className="mx-auto mt-2 max-w-3xl text-[10px] leading-5 text-slate-500">Shyena provides intelligence and orchestration. Your cloud, runners, environments, frameworks and tools remain yours.</div></div><div className="mt-6 grid gap-px border border-slate-300 bg-slate-300 sm:grid-cols-2 lg:grid-cols-3">{infra.map(([t,d,Icon])=><div key={t} className="bg-[#f8fafc] p-4 sm:p-5"><div className="flex items-center gap-3"><Icon className="h-4 w-4"/><div className="text-xs font-extrabold">{t}</div></div><div className="mt-2 text-[9px] leading-4 text-slate-500">{d}</div></div>)}</div></div>
      <Connector />
      <div className="grid w-full gap-3 lg:grid-cols-3">{[["04 · Execution signals","Tests + runtime evidence","Browser, API, data, logs, traces and history return to the quality context."],["05 · Assurance","Investigate + evaluate","Classify failures, correlate signals, protect assertions and produce reviewable evidence."],["06 · Evidence graph","Trace intent to proof","Requirement → rule → risk/control → test intent → execution → evidence → evaluation → remediation → re-test."]].map(([e,t,d],i)=><div key={e} className={i===1?"border border-slate-900 bg-[#0b0920] p-5 text-white":"border border-slate-300 bg-white p-5"}><div className={i===1?"font-mono text-[9px] uppercase tracking-[.18em] text-[#ffb703]":"font-mono text-[9px] uppercase tracking-[.18em] text-slate-400"}>{e}</div><div className="mt-2 text-sm font-extrabold">{t}</div><div className={i===1?"mt-2 text-[9px] leading-5 text-white/45":"mt-2 text-[9px] leading-5 text-slate-500"}>{d}</div></div>)}</div>
      <Connector />
      <div className="grid w-full gap-3 lg:grid-cols-[1fr_70px_1fr] lg:items-center"><div className="border border-slate-300 bg-white p-6 text-center"><div className="font-mono text-[9px] uppercase tracking-[.18em] text-slate-400">07 · Risk assessment</div><div className="mt-2 text-lg font-extrabold">What changed. What matters.</div><div className="mt-2 text-[9px] leading-5 text-slate-500">Impact, coverage, failures and evidence become a decision-ready quality view.</div></div><ArrowRight className="mx-auto hidden h-5 w-5 lg:block"/><div className="border border-slate-900 bg-[#0b0920] p-6 text-center text-white"><div className="font-mono text-[9px] uppercase tracking-[.18em] text-[#ffb703]">08 · Human decision</div><div className="mt-2 font-[Sora] text-2xl font-extrabold">GO / NO-GO</div><div className="mt-2 text-[9px] leading-5 text-white/45">Testers own the quality and release decision. Shyena makes the evidence actionable.</div></div></div>
    </div></div>
  </div>;
}

function AutonomousTestingPage() {
  return <main className="overflow-hidden bg-white text-slate-950">
    <section className="border-b border-slate-300"><div className="mx-auto max-w-[1440px] px-6 py-12 sm:px-8 lg:px-10 lg:py-16"><div className="mx-auto max-w-6xl text-center"><div className="mb-5 inline-flex items-center gap-2 border border-slate-300 px-3 py-2 font-mono text-[9px] font-bold uppercase tracking-[.2em] text-slate-500"><span className="h-2 w-2 rounded-full bg-[#ffb703]"/> Autonomous quality engineering</div><h1 className="font-[Sora] text-[clamp(3rem,6.5vw,6.5rem)] font-extrabold leading-[.88] tracking-[-.075em]">Make testing <span className="text-slate-500">self-driving.</span></h1><h2 className="mt-3 font-[Sora] text-[clamp(2rem,4vw,4rem)] font-extrabold leading-[.94] tracking-[-.06em]">Make testers more strategic.</h2><p className="mx-auto mt-6 max-w-4xl text-lg font-medium leading-8 text-slate-700 sm:text-xl">Shyena agents autonomously plan, automate, execute and investigate testing through the infrastructure you already operate—so testers can focus on risk, quality and release decisions.</p><p className="mx-auto mt-3 max-w-3xl text-sm leading-6 text-slate-500">The goal is not more automated tests. The goal is faster feedback, stronger evidence and more confident releases.</p><div className="mt-7 flex flex-wrap justify-center gap-3"><Link to="/contact" className="inline-flex h-12 items-center gap-2 border border-[#ffb703] bg-[#ffb703] px-6 text-sm font-extrabold uppercase">See Shyena agents <ArrowRight className="h-5 w-5"/></Link><a href="#flow" className="inline-flex h-12 items-center border border-slate-400 px-6 text-sm font-semibold">See the flow</a></div></div></div></section>
    <section className="border-b border-slate-300 bg-[#f8fafc]"><div className="mx-auto grid max-w-[1440px] gap-8 px-6 py-12 sm:px-8 lg:grid-cols-2 lg:px-10 lg:py-16"><div><div className="font-mono text-[10px] font-bold uppercase tracking-[.2em] text-[#a87900]">The problem</div><h2 className="mt-3 font-[Sora] text-[clamp(2.3rem,4vw,4.2rem)] font-extrabold leading-[.94] tracking-[-.06em]">AI accelerated software delivery. Testing has to catch up.</h2></div><div className="space-y-5 text-sm leading-7 text-slate-600"><p>AI-assisted development increases the pace and volume of change. Traditional automation responds with more scripts, more maintenance and more manual failure analysis.</p><p>That creates a <strong className="text-slate-950">verification gap</strong>: more testing activity does not automatically mean more confidence.</p><div className="border-l-4 border-[#ffb703] pl-5 text-base font-bold leading-7 text-slate-950">Shyena closes the gap by making testing self-driving while keeping quality and release accountability with people.</div></div></div></section>
    <section id="flow" className="border-b border-slate-300"><div className="mx-auto max-w-[1440px] px-6 py-10 sm:px-8 lg:px-10 lg:py-14"><div className="mx-auto mb-8 max-w-4xl text-center"><div className="font-mono text-[10px] font-bold uppercase tracking-[.2em] text-[#a87900]">One autonomous flow</div><h2 className="mt-3 font-[Sora] text-[clamp(2rem,3.8vw,3.7rem)] font-extrabold leading-[.95] tracking-[-.055em]">Agents do the testing. People own the decisions.</h2><p className="mt-4 text-sm leading-6 text-slate-600">One connected path from change to release confidence.</p></div><Flow/></div></section>
    <section className="border-b border-slate-300 bg-[#0b0920] text-white"><div className="mx-auto max-w-[1440px] px-6 py-12 sm:px-8 lg:px-10 lg:py-16"><div className="mx-auto max-w-6xl"><div className="font-mono text-[10px] font-bold uppercase tracking-[.2em] text-[#ffb703]">The workforce shift</div><h2 className="mt-3 max-w-5xl font-[Sora] text-[clamp(2.3rem,4vw,4.4rem)] font-extrabold leading-[.94] tracking-[-.06em]">Move testers from test execution to intelligent quality decisions.</h2><p className="mt-5 max-w-3xl text-base leading-7 text-white/55">Automate the repetitive work. Increase the leverage of the people who understand the product, business and risk.</p><div className="mt-9 grid border border-white/10 sm:grid-cols-2 lg:grid-cols-3">{shifts.map(([a,b],i)=><div key={a} className="border-b border-r border-white/10 p-5"><div className="font-mono text-[9px] font-bold text-[#ffb703]">0{i+1}</div><div className="mt-3 text-[9px] font-bold uppercase tracking-[.14em] text-white/30">Today</div><div className="mt-1 text-sm font-extrabold">{a}</div><div className="mt-4 text-[9px] font-bold uppercase tracking-[.14em] text-[#ffb703]">With Shyena</div><div className="mt-1 text-sm font-semibold text-white/70">{b}</div></div>)}</div></div></div></section>
    <section className="border-b border-slate-300 bg-[#ffb703]"><div className="mx-auto max-w-[1440px] px-6 py-12 sm:px-8 lg:px-10 lg:py-14"><div className="mx-auto max-w-6xl"><div className="font-mono text-[10px] font-bold uppercase tracking-[.2em] text-slate-800/60">The enterprise advantage</div><h2 className="mt-3 max-w-5xl font-[Sora] text-[clamp(2.3rem,4vw,4.4rem)] font-extrabold leading-[.94] tracking-[-.055em]">Keep the infrastructure. Change how testing works.</h2><div className="mt-8 grid gap-3 md:grid-cols-2 lg:grid-cols-4">{[["No rip-and-replace","Your frameworks, environments, CI/CD and observability stay in place."],["Existing investments","Shyena works through the testing assets your teams already operate."],["Controlled autonomy","Agents automate defined work while assertions, risk and governance remain protected."],["Decision-ready evidence","Testing becomes evidence for quality and release decisions, not just pass/fail output."]].map(([a,b])=><div key={a} className="bg-white/40 p-5"><div className="text-sm font-extrabold">{a}</div><div className="mt-2 text-xs leading-5 text-slate-800/65">{b}</div></div>)}</div></div></div></section>
    <section className="border-b border-slate-300"><div className="mx-auto grid max-w-[1440px] gap-8 px-6 py-12 sm:px-8 lg:grid-cols-[1fr_1fr] lg:px-10 lg:py-16"><div><div className="font-mono text-[10px] font-bold uppercase tracking-[.2em] text-[#a87900]">One connected platform</div><h2 className="mt-3 font-[Sora] text-[clamp(2.3rem,4vw,4.2rem)] font-extrabold leading-[.94] tracking-[-.06em]">Autonomous testing. Evidence-backed assurance.</h2></div><div className="grid gap-3 sm:grid-cols-2"><Link to="/nexus" className="group border border-slate-300 p-5 hover:border-slate-900"><div className="font-mono text-[9px] text-slate-400">NEXUS · UNDERSTAND</div><div className="mt-3 text-lg font-extrabold">Know the system.</div><div className="mt-2 text-xs leading-5 text-slate-500">Map behaviour, flows, intents, dependencies and impact.</div><ArrowRight className="mt-5 h-4 w-4 group-hover:translate-x-1"/></Link><Link to="/vera" className="group border border-slate-300 p-5 hover:border-slate-900"><div className="font-mono text-[9px] text-slate-400">VERA · TEST & EVALUATE</div><div className="mt-3 text-lg font-extrabold">Test what matters.</div><div className="mt-2 text-xs leading-5 text-slate-500">Execute realistic behaviour and evaluate whether results are trustworthy.</div><ArrowRight className="mt-5 h-4 w-4 group-hover:translate-x-1"/></Link><Link to="/chakra" className="group border border-slate-300 p-5 hover:border-slate-900 sm:col-span-2"><div className="font-mono text-[9px] text-slate-400">CHAKRA · SECURE</div><div className="mt-3 text-lg font-extrabold">Protect the release.</div><div className="mt-2 text-xs leading-5 text-slate-500">Carry verified security findings into the release decision.</div><ArrowRight className="mt-5 h-4 w-4 group-hover:translate-x-1"/></Link></div></div></section>
    <section><div className="mx-auto max-w-[1440px] px-6 py-14 text-center sm:px-8 lg:px-10 lg:py-20"><Users className="mx-auto h-8 w-8"/><div className="mt-5 font-mono text-[10px] font-bold uppercase tracking-[.2em] text-[#a87900]">Mission</div><h2 className="mx-auto mt-3 max-w-5xl font-[Sora] text-[clamp(2.5rem,5vw,5.5rem)] font-extrabold leading-[.9] tracking-[-.07em]">Make testing self-driving.<br/><span className="text-slate-500">Make testers more strategic.</span></h2><p className="mx-auto mt-6 max-w-3xl text-base leading-7 text-slate-600">Shyena agents take care of the automation work. Testers focus on risk, quality and the decisions that require human judgment.</p><div className="mt-8"><Link to="/contact" className="inline-flex h-12 items-center gap-2 border border-[#ffb703] bg-[#ffb703] px-6 text-sm font-extrabold uppercase">Talk to Shyena <ArrowRight className="h-5 w-5"/></Link></div></div></section>
  </main>;
}
