import { createFileRoute, Link } from "@tanstack/react-router";
import {
  Activity,
  ArrowRight,
  Bot,
  Check,
  Code2,
  FileCheck2,
  Globe2,
  Layers3,
  Play,
  ShieldCheck,
  Target,
  Workflow,
} from "lucide-react";

export const Route = createFileRoute("/autonomous-testing")({
  head: () => ({
    meta: [
      { title: "Autonomous Testing | Shyena" },
      { name: "description", content: "Autonomous testing for modern engineering teams. Shyena understands the application, engineers Playwright automation, reviews coverage, diagnoses failures and produces release evidence." },
      { name: "keywords", content: "autonomous testing, agentic testing, AI test automation, Playwright automation, autonomous QA, quality engineering" },
      { property: "og:title", content: "Autonomous Testing | Shyena" },
      { property: "og:description", content: "Give Shyena a testing goal. It understands the system, engineers the automation, challenges coverage and proves the result." },
      { property: "og:type", content: "website" },
      { name: "twitter:card", content: "summary_large_image" },
    ],
    links: [{ rel: "canonical", href: "https://www.shyena.eu/autonomous-testing" }],
  }),
  component: AutonomousTestingPage,
});

const capabilities = [
  ["01", "Application intelligence", "Understand the application before writing a test: journeys, pages, APIs, states, dependencies and existing automation.", Globe2],
  ["02", "Autonomous test engineering", "Turn a quality goal into scenarios, fixtures, data and repository-native Playwright automation without starting from a blank file.", Code2],
  ["03", "Independent assurance review", "Challenge generated coverage against critical journeys, requirements, risk and application behaviour before execution.", ShieldCheck],
  ["04", "Failure intelligence", "Correlate browser evidence, APIs, logs, code changes and history to determine what actually failed and why.", Activity],
] as const;

const useCases = [
  ["Web applications", "Discover real user journeys and continuously engineer browser automation.", Globe2],
  ["API-led systems", "Validate API behaviour alongside the customer journey and supporting services.", Workflow],
  ["Enterprise platforms", "Work across CRM, ERP, commerce and operational applications without changing the assurance model.", Layers3],
  ["AI applications", "Extend autonomous testing into agentic workflows, tools, RAG and multi-step behaviour.", Bot],
] as const;

const steps = [
  ["01", "Give Shyena a goal", "A journey, requirement, capability, risk or release objective."],
  ["02", "Understand the system", "Explore the application and connect the available engineering context."],
  ["03", "Find what matters", "Map risk, critical paths, dependencies and coverage gaps."],
  ["04", "Engineer the tests", "Generate maintainable Playwright automation, fixtures and supporting assets."],
  ["05", "Challenge and execute", "Review the suite, run it and capture the evidence behind every result."],
  ["06", "Diagnose and improve", "Classify failures, apply governed repairs and carry learning into the next run."],
] as const;

function HeroProductVisual() {
  return <div className="relative border border-slate-700 bg-[#080711] shadow-[0_30px_80px_-35px_rgba(15,23,42,.65)]">
    <div className="flex items-center justify-between border-b border-white/10 bg-[#0d0a1c] px-5 py-4 text-xs text-white/60"><span className="flex items-center gap-2"><span className="h-2 w-2 rounded-full bg-emerald-400" /> Autonomous test mission</span><span className="font-mono tracking-wide text-white/35">SHYENA · RUN 0248</span></div>
    <div className="p-5 sm:p-7">
      <div className="flex items-center justify-between gap-4"><div><div className="font-mono text-[9px] uppercase tracking-[0.2em] text-white/35">Quality objective</div><div className="mt-2 text-lg font-bold text-white">Prove checkout end-to-end</div></div><div className="border border-[#ffb703]/40 bg-[#ffb703]/10 px-3 py-2 text-[10px] font-bold uppercase tracking-[0.14em] text-[#ffcf4d]">Autonomous</div></div>
      <div className="mt-6 grid grid-cols-2 gap-2 sm:grid-cols-4">{[["Application", "Understood", "100%"], ["Risk", "Mapped", "18"], ["Coverage", "Reviewed", "94%"], ["Evidence", "Ready", "27"]].map(([a, b, c]) => <div key={a} className="border border-white/10 bg-white/[0.035] p-3"><div className="font-mono text-[8px] uppercase tracking-[0.16em] text-white/35">{a}</div><div className="mt-2 text-xs font-semibold text-white/70">{b}</div><div className="mt-1 text-lg font-extrabold text-white">{c}</div></div>)}</div>
      <div className="mt-5 border border-white/10 bg-[#0e0c20] p-4"><div className="mb-4 flex items-center justify-between"><span className="font-mono text-[9px] uppercase tracking-[0.18em] text-white/35">Autonomous assurance flow</span><span className="text-[9px] font-bold uppercase text-emerald-400">Live</span></div><div className="grid gap-2 sm:grid-cols-5">{[["Understand", "Application"], ["Analyze", "Risk + gaps"], ["Engineer", "Playwright"], ["Execute", "Evidence"], ["Prove", "Verdict"]].map(([x, y], i) => <div key={x} className="relative border border-white/10 bg-white/[0.025] p-3"><div className="font-mono text-[8px] text-white/30">0{i + 1}</div><div className="mt-2 text-xs font-bold text-white">{x}</div><div className="mt-1 text-[9px] text-white/40">{y}</div>{i < 4 && <ArrowRight className="absolute -right-2 top-7 z-10 hidden h-3 w-3 text-[#ffb703] sm:block" />}</div>)}</div></div>
      <div className="mt-5 grid gap-2 sm:grid-cols-[1.4fr_1fr]"><div className="border border-white/10 bg-white/[0.025] p-4"><div className="font-mono text-[8px] uppercase tracking-[0.16em] text-white/30">Latest finding</div><div className="mt-2 flex items-center gap-2 text-sm font-semibold text-white"><span className="h-2 w-2 bg-[#ffb703]" /> Payment failure path needs assertion</div><div className="mt-2 text-[10px] leading-4 text-white/40">Review agent flagged an outcome gap before release.</div></div><div className="border border-emerald-400/20 bg-emerald-400/[0.06] p-4"><div className="font-mono text-[8px] uppercase tracking-[0.16em] text-emerald-300/50">Release signal</div><div className="mt-2 text-sm font-extrabold text-emerald-300">Conditional</div><div className="mt-1 text-[10px] text-white/40">1 action before approval</div></div></div>
    </div>
  </div>;
}

function CapabilityCard({ item }: { item: (typeof capabilities)[number] }) {
  const [number, title, text, Icon] = item;
  return <article className="group min-h-[310px] border border-slate-300 bg-white p-7 transition-all hover:-translate-y-1 hover:border-slate-950 hover:shadow-[0_20px_45px_-30px_rgba(15,23,42,.4)] sm:p-8"><div className="flex items-start justify-between"><span className="font-mono text-xs tracking-[0.16em] text-slate-400">{number}</span><div className="flex h-11 w-11 items-center justify-center border border-slate-300 group-hover:border-[#ffb703] group-hover:bg-[#ffb703]"><Icon className="h-5 w-5 text-slate-900" /></div></div><h3 className="mt-12 font-[Sora] text-2xl font-extrabold tracking-[-0.035em]">{title}</h3><p className="mt-4 text-sm leading-7 text-slate-600">{text}</p><div className="mt-7 h-1 w-10 bg-[#ffb703] transition-all group-hover:w-20" /></article>;
}

function AutonomousTestingPage() {
  return <main className="overflow-hidden bg-white text-slate-950">
    <section className="border-b border-slate-300 bg-white"><div className="mx-auto grid max-w-[1440px] gap-12 px-6 pb-14 pt-12 sm:px-8 sm:pb-20 lg:grid-cols-[0.88fr_1.12fr] lg:items-center lg:gap-16 lg:px-10 lg:py-20"><div><div className="mb-6 border-l-4 border-[#ffb703] pl-4 font-mono text-xs font-bold uppercase tracking-[0.2em] text-slate-600">Autonomous quality engineering</div><h1 className="max-w-3xl font-[Sora] text-[clamp(2.75rem,4.8vw,5rem)] font-extrabold leading-[0.96] tracking-[-0.06em]">Give Shyena the goal.<br /><span className="text-slate-500">It engineers the testing.</span></h1><p className="mt-7 max-w-2xl text-lg leading-8 text-slate-600 sm:text-[19px]">Stop treating test automation as a collection of scripts. Shyena understands the application, finds what matters, engineers the automation, challenges the coverage and turns execution into evidence.</p><div className="mt-8 flex flex-wrap gap-3"><Link to="/contact" className="inline-flex h-12 items-center gap-2 border border-[#ffb703] bg-[#ffb703] px-7 text-sm font-extrabold uppercase text-slate-950">See autonomous testing <ArrowRight className="h-5 w-5" /></Link><a href="#capabilities" className="inline-flex h-12 items-center gap-2 border border-slate-400 bg-white px-7 text-sm font-semibold text-slate-950"><Play className="h-4 w-4" /> Explore the platform</a></div><div className="mt-7 flex flex-wrap gap-x-5 gap-y-2 text-[10px] font-bold uppercase tracking-[0.16em] text-slate-400">Application intelligence · Playwright · Risk · Failure intelligence · Evidence</div></div><HeroProductVisual /></div></section>

    <section className="border-b border-slate-300 bg-[#f8fafc]"><div className="mx-auto max-w-[1440px] px-6 py-9 sm:px-8 lg:px-10 lg:py-11"><div className="grid gap-px border border-slate-300 bg-slate-300 sm:grid-cols-2 lg:grid-cols-4">{[["UNDERSTAND", "The system", "Application + repository context"], ["ENGINEER", "The assurance", "Scenarios + Playwright automation"], ["CHALLENGE", "The coverage", "Risk + blind-spot review"], ["PROVE", "The outcome", "Evidence + release signal"]].map(([a, b, c]) => <div key={a} className="bg-white p-6"><div className="font-mono text-[9px] font-bold tracking-[0.18em] text-[#a87900]">{a}</div><div className="mt-2 text-lg font-extrabold">{b}</div><div className="mt-1 text-xs text-slate-500">{c}</div></div>)}</div></div></section>

    <section id="capabilities" className="border-b border-slate-300 bg-white"><div className="mx-auto max-w-[1440px] px-6 py-14 sm:px-8 lg:px-10 lg:py-18"><div className="grid gap-8 border-b border-slate-300 pb-9 lg:grid-cols-[1fr_430px] lg:items-end"><div><div className="font-mono text-xs font-bold uppercase tracking-[0.2em] text-[#a87900]">One autonomous testing platform</div><h2 className="mt-4 max-w-4xl font-[Sora] text-[clamp(2.4rem,4vw,4rem)] font-extrabold leading-[0.98] tracking-[-0.05em]">Everything between a testing goal and trustworthy evidence.</h2></div><p className="max-w-md text-base leading-7 text-slate-600">The value is not another AI code generator. Shyena connects the engineering work around testing into one autonomous operating model.</p></div><div className="mt-9 grid gap-px border border-slate-300 bg-slate-300 md:grid-cols-2 lg:grid-cols-4">{capabilities.map((item) => <CapabilityCard key={item[1]} item={item} />)}</div></div></section>

    <section className="border-b border-slate-300 bg-[#0b0920] text-white"><div className="mx-auto max-w-[1440px] px-6 py-14 sm:px-8 lg:px-10 lg:py-18"><div className="grid gap-10 lg:grid-cols-[0.78fr_1.22fr] lg:items-center"><div><div className="font-mono text-xs font-bold uppercase tracking-[0.2em] text-[#ffb703]">The system behind the automation</div><h2 className="mt-4 max-w-2xl font-[Sora] text-[clamp(2.4rem,4vw,4rem)] font-extrabold leading-[0.98] tracking-[-0.05em]">A living model of the application.</h2><p className="mt-6 max-w-xl text-lg leading-8 text-white/60">Shyena builds application intelligence from what the system exposes and uses that context across planning, generation, execution, diagnosis and evidence.</p></div><div className="border border-white/10 bg-white/[0.035] p-5 sm:p-7"><div className="flex items-center justify-between border-b border-white/10 pb-4"><span className="font-mono text-[9px] uppercase tracking-[0.2em] text-white/35">Application intelligence graph</span><span className="text-[9px] font-bold uppercase tracking-[0.15em] text-emerald-400">Connected</span></div><div className="relative mt-6 grid grid-cols-3 gap-2 sm:grid-cols-5">{[["Application", Globe2], ["Behaviour", Workflow], ["Tests", Code2], ["Risk", Target], ["Evidence", FileCheck2]].map(([label, Icon]) => <div key={label as string} className="relative flex min-h-[115px] flex-col items-center justify-center border border-white/10 bg-[#111022] p-3 text-center"><Icon className="h-5 w-5 text-[#ffb703]" /><div className="mt-3 text-xs font-bold text-white">{label as string}</div><div className="mt-1 text-[9px] leading-4 text-white/35">linked context</div></div>)}</div><div className="mt-4 grid gap-2 sm:grid-cols-3"><div className="border border-white/10 p-4"><div className="text-[9px] uppercase tracking-[0.16em] text-white/30">Change</div><div className="mt-2 text-sm font-bold">Code + dependency impact</div></div><div className="border border-white/10 p-4"><div className="text-[9px] uppercase tracking-[0.16em] text-white/30">Decision</div><div className="mt-2 text-sm font-bold">Risk-weighted coverage</div></div><div className="border border-white/10 p-4"><div className="text-[9px] uppercase tracking-[0.16em] text-white/30">Memory</div><div className="mt-2 text-sm font-bold">Previous runs + findings</div></div></div></div></div></div></section>

    <section className="border-b border-slate-300 bg-white"><div className="mx-auto max-w-[1440px] px-6 py-14 sm:px-8 lg:px-10 lg:py-18"><div className="grid gap-10 lg:grid-cols-[0.72fr_1.28fr] lg:items-start"><div><div className="font-mono text-xs font-bold uppercase tracking-[0.2em] text-[#a87900]">From goal to evidence</div><h2 className="mt-4 max-w-xl font-[Sora] text-[clamp(2.4rem,4vw,4rem)] font-extrabold leading-[0.98] tracking-[-0.05em]">A single autonomous loop.</h2><p className="mt-6 max-w-xl text-lg leading-8 text-slate-600">Every stage contributes context to the next. The output is not simply a green test; it is evidence that can support an engineering decision.</p></div><div className="grid border-t border-slate-300 sm:grid-cols-2 lg:grid-cols-3">{steps.map(([n, title, text]) => <article key={n} className="group border-b border-slate-300 p-6 sm:p-7"><div className="flex items-center justify-between"><span className="font-mono text-xs text-slate-400">{n}</span><ArrowRight className="h-4 w-4 text-slate-300 transition-transform group-hover:translate-x-1 group-hover:text-slate-900" /></div><h3 className="mt-8 text-xl font-extrabold">{title}</h3><p className="mt-3 text-sm leading-6 text-slate-600">{text}</p></article>)}</div></div></div></section>

    <section className="border-b border-slate-300 bg-[#f8fafc]"><div className="mx-auto max-w-[1440px] px-6 py-14 sm:px-8 lg:px-10 lg:py-18"><div className="grid gap-8 border-b border-slate-300 pb-9 lg:grid-cols-[1fr_430px] lg:items-end"><div><div className="font-mono text-xs font-bold uppercase tracking-[0.2em] text-[#a87900]">Where it fits</div><h2 className="mt-4 max-w-4xl font-[Sora] text-[clamp(2.4rem,4vw,4rem)] font-extrabold leading-[0.98] tracking-[-0.05em]">One assurance model across your technology landscape.</h2></div><p className="max-w-md text-base leading-7 text-slate-600">Start with what the team needs to prove. The assurance model adapts to the application and the tools already around it.</p></div><div className="mt-9 grid gap-px border border-slate-300 bg-slate-300 md:grid-cols-2 lg:grid-cols-4">{useCases.map(([title, text, Icon]) => <article key={title} className="group min-h-[245px] bg-white p-7 transition-colors hover:bg-slate-50"><div className="flex h-11 w-11 items-center justify-center border border-slate-300 group-hover:border-[#ffb703] group-hover:bg-[#ffb703]"><Icon className="h-5 w-5" /></div><h3 className="mt-9 text-xl font-extrabold">{title}</h3><p className="mt-3 text-sm leading-7 text-slate-600">{text}</p></article>)}</div><div className="mt-8 flex flex-wrap gap-2">{["Playwright", "Git", "CI/CD", "APIs", "Observability", "CRM", "ERP", "Cloud applications", "Agentic workflows"].map((item) => <span key={item} className="border border-slate-300 bg-white px-3 py-2 text-[10px] font-bold uppercase tracking-[0.12em] text-slate-600">{item}</span>)}</div></div></section>

    <section className="border-b border-slate-300 bg-white"><div className="mx-auto max-w-[1440px] px-6 py-14 sm:px-8 lg:px-10 lg:py-18"><div className="grid gap-10 lg:grid-cols-[0.82fr_1.18fr] lg:items-center"><div><div className="font-mono text-xs font-bold uppercase tracking-[0.2em] text-[#a87900]">Why teams move beyond test generation</div><h2 className="mt-4 max-w-xl font-[Sora] text-[clamp(2.4rem,4vw,4rem)] font-extrabold leading-[0.98] tracking-[-0.05em]">Generating code is not the same as engineering assurance.</h2><p className="mt-6 max-w-xl text-lg leading-8 text-slate-600">Shyena is designed around the work that surrounds automation: understanding, deciding, reviewing, diagnosing, repairing and proving.</p></div><div className="grid gap-px border border-slate-300 bg-slate-300"><div className="grid grid-cols-[0.7fr_1fr] bg-white p-5 sm:p-6"><div className="font-mono text-[10px] font-bold uppercase tracking-[0.16em] text-slate-400">Traditional</div><div className="text-sm font-semibold text-slate-600">People write → maintain → triage → decide</div></div><div className="grid grid-cols-[0.7fr_1fr] bg-white p-5 sm:p-6"><div className="font-mono text-[10px] font-bold uppercase tracking-[0.16em] text-slate-400">AI-assisted</div><div className="text-sm font-semibold text-slate-600">People define → AI generates code → people own the rest</div></div><div className="grid grid-cols-[0.7fr_1fr] border-l-4 border-[#ffb703] bg-[#fffaf0] p-5 sm:p-6"><div className="font-mono text-[10px] font-bold uppercase tracking-[0.16em] text-slate-700">Shyena</div><div className="text-sm font-extrabold text-slate-950">Define the outcome → agents engineer the assurance loop → evidence-backed decision</div></div></div></div></div></section>

    <section className="border-b border-slate-300 bg-[#0b0920] text-white"><div className="mx-auto max-w-[1440px] px-6 py-14 sm:px-8 lg:px-10 lg:py-18"><div className="grid gap-10 lg:grid-cols-[0.8fr_1.2fr] lg:items-center"><div><div className="font-mono text-xs font-bold uppercase tracking-[0.2em] text-[#ffb703]">Evidence-backed release</div><h2 className="mt-4 max-w-2xl font-[Sora] text-[clamp(2.4rem,4vw,4rem)] font-extrabold leading-[0.98] tracking-[-0.05em]">Know what passed. Know what failed. Know why.</h2><p className="mt-6 max-w-xl text-lg leading-8 text-white/60">Execution evidence, coverage findings and failure intelligence stay connected so teams can act on the result instead of starting an investigation from scratch.</p></div><div className="border border-white/10 bg-white/[0.035] p-5 sm:p-7"><div className="flex items-center justify-between border-b border-white/10 pb-4"><span className="font-mono text-[9px] uppercase tracking-[0.2em] text-white/35">Assurance result</span><span className="border border-[#ffb703]/30 bg-[#ffb703]/10 px-3 py-1.5 text-[9px] font-bold uppercase text-[#ffcf4d]">Conditional pass</span></div><div className="mt-5 grid gap-3 sm:grid-cols-2">{[["Execution", "142 / 148", "scenarios passed"], ["Coverage", "94%", "risk-weighted review"], ["Failures", "4", "classified with evidence"], ["Remediation", "2", "automation fixes proposed"]].map(([a, b, c]) => <div key={a} className="border border-white/10 p-4"><div className="text-[9px] uppercase tracking-[0.16em] text-white/30">{a}</div><div className="mt-2 text-xl font-bold">{b}</div><div className="mt-1 text-xs text-white/40">{c}</div></div>)}</div><div className="mt-4 flex items-center gap-3 border-t border-white/10 pt-4 text-sm text-white/65"><Check className="h-4 w-4 text-[#ffb703]" /> Trace, findings and decision remain linked.</div></div></div></div></section>

    <section className="bg-[#ffb703] text-slate-950"><div className="mx-auto flex max-w-[1440px] flex-col gap-8 px-6 py-14 sm:px-8 lg:flex-row lg:items-center lg:justify-between lg:px-10 lg:py-16"><div><div className="font-mono text-xs font-bold uppercase tracking-[0.2em] text-slate-700">Autonomous testing by Shyena</div><h2 className="mt-4 max-w-4xl font-[Sora] text-[clamp(2.4rem,4vw,4rem)] font-extrabold leading-[0.98] tracking-[-0.05em]">You define what must be proven. Shyena engineers the proof.</h2><p className="mt-5 max-w-3xl text-base leading-7 text-slate-800 sm:text-lg">Move from testing intent to executable assurance, independent review, failure intelligence and evidence-backed release confidence.</p></div><Link to="/contact" className="inline-flex h-14 shrink-0 items-center justify-center gap-3 border border-slate-950 bg-slate-950 px-7 text-sm font-extrabold uppercase text-white transition-transform hover:-translate-y-0.5">See Shyena in action <ArrowRight className="h-4 w-4" /></Link></div></section>
  </main>;
}
