import { ArrowLeft, ArrowRight, Coins, Eye, Gauge, ShieldCheck, Workflow } from "lucide-react";
import { createFileRoute, Link } from "@tanstack/react-router";

const ACTS = [
  { number: "01", label: "ACT 1", title: "The Problem", items: [["1", "From Model Evaluation to System Assurance"], ["2", "The Agentic Harness Is an Assurance Surface"], ["3", "Tokenomics Reveals the Hidden Execution"], ["4", "Functional vs Assurance Inference"]] },
  { number: "02", label: "ACT 2", title: "The Economics of Trust", items: [["5", "The Cost of Trust"], ["6", "Assurance Efficiency"], ["7", "The Cheapest Agent Is Not Necessarily the Most Efficient"], ["8", "Assurance Waste"], ["9", "Every Token Should Have a Reason"]] },
  { number: "03", label: "ACT 3", title: "Evidence & Continuous Assurance", items: [["10", "Observability Becomes the Evidence Backbone"], ["11", "Tokenomics Can Reveal Behavioural Problems"], ["12", "Tokenomics as a Release-Gate Signal"], ["13", "A Unified Evidence Model"], ["14", "From Cost per Token to Cost per Assured Business Outcome"], ["15", "The Assurance Equation"], ["16", "AI Assurance Becomes Continuous"]] },
  { number: "04", label: "ACT 4", title: "Shyena", items: [["17", "What Shyena Changes"], ["18", "The Future of Agentic AI Economics"], ["19", "Toward an Assurance Score for Agentic Systems"]] },
  { number: "05", label: "ACT 5", title: "The Strategic Conclusion", items: [["20", "The New AI Assurance Question"]] },
] as const;

export const Route = createFileRoute("/docs/ai-assurance-tokenomics")({
  head: () => ({
    meta: [
      { title: "AI Assurance Tokenomics | Shyena Docs" },
      { name: "description", content: "AI Assurance Tokenomics: measuring the cost of trust across quality, safety, security, reliability, governance, economics and business outcomes in agentic AI." },
      { property: "og:title", content: "AI Assurance Tokenomics | Shyena Docs" },
      { property: "og:description", content: "From inference to impact: a complete assurance journey for agentic AI." },
      { property: "og:type", content: "article" },
      { property: "og:image", content: "https://www.shyena.eu/ai-assurance-tokenomics-acts.svg" },
    ],
    links: [{ rel: "canonical", href: "https://www.shyena.eu/docs/ai-assurance-tokenomics" }],
  }),
  component: Article,
});

function Section({ id, title, children }: { id: string; title: string; children: React.ReactNode }) {
  return <section id={id} className="scroll-mt-28 border-t border-slate-200 pt-12 first:border-0 first:pt-0"><h2 className="text-2xl font-bold tracking-tight text-[#0e172b] sm:text-3xl">{title}</h2><div className="mt-5 space-y-5 text-[17px] leading-8 text-slate-700">{children}</div></section>;
}
function Quote({ children }: { children: React.ReactNode }) { return <blockquote className="border-l-2 border-[#c89b3c] bg-[#fbf8ef] px-6 py-5 text-xl font-medium leading-8 text-[#0e172b]">{children}</blockquote>; }
function CodeLine({ children }: { children: React.ReactNode }) { return <div className="overflow-x-auto rounded-md border border-slate-200 bg-[#f7f7f5] px-5 py-4 font-mono text-sm leading-7 text-[#17233a]">{children}</div>; }
function Metric({ icon: Icon, title, children }: { icon: typeof Coins; title: string; children: React.ReactNode }) { return <div className="border border-slate-200 bg-white p-5"><Icon className="h-5 w-5 text-[#b4872c]" /><h3 className="mt-4 font-semibold text-[#0e172b]">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{children}</p></div>; }

function Article() {
  return <div className="bg-white text-slate-950">
    <section className="border-b border-slate-200 bg-[#f7f4ec]"><div className="mx-auto max-w-7xl px-5 py-8 sm:px-8"><Link to="/docs" className="inline-flex items-center gap-2 text-sm font-semibold text-slate-600 hover:text-[#0e172b]"><ArrowLeft className="h-4 w-4" /> Documentation</Link></div></section>
    <header className="border-b border-slate-200 bg-white"><div className="mx-auto max-w-6xl px-5 py-14 sm:px-8 sm:py-20">
      <div className="max-w-4xl"><p className="font-mono text-xs uppercase tracking-[0.22em] text-[#a87900]">AI Assurance / Tokenomics</p><h1 className="mt-5 text-5xl font-bold leading-[1.02] tracking-[-0.045em] text-[#0e172b] sm:text-7xl">AI Assurance Tokenomics</h1><p className="mt-5 text-xl leading-8 text-slate-600 sm:text-2xl">Measuring the cost of trust in agentic AI — from inference to impact.</p><div className="mt-8 flex flex-wrap gap-3 text-xs font-semibold uppercase tracking-[0.14em] text-slate-500"><span className="border border-slate-300 px-3 py-2">Quality</span><span className="border border-slate-300 px-3 py-2">Safety</span><span className="border border-slate-300 px-3 py-2">Security</span><span className="border border-slate-300 px-3 py-2">Reliability</span><span className="border border-slate-300 px-3 py-2">Economics</span></div></div>
      <figure className="mt-12 overflow-hidden rounded-xl border border-slate-200 bg-[#f7f4ec] shadow-[0_18px_60px_-42px_rgba(15,23,42,0.45)]"><img src="/ai-assurance-tokenomics-acts.svg" alt="AI Assurance Tokenomics five-act journey: The Problem, The Economics of Trust, Evidence and Continuous Assurance, Shyena, and The Strategic Conclusion" className="h-auto w-full" /><figcaption className="border-t border-slate-200 px-5 py-3 text-xs text-slate-500 sm:px-7">AI Assurance Tokenomics — the five-act assurance journey from inference to impact.</figcaption></figure>
    </div></header>

    <main className="mx-auto max-w-6xl px-5 py-14 sm:px-8 sm:py-20"><div className="grid gap-12 lg:grid-cols-[240px_minmax(0,1fr)] lg:items-start lg:gap-16">
      <aside className="lg:sticky lg:top-24"><p className="font-mono text-[10px] uppercase tracking-[0.18em] text-[#a87900]">On this page</p><nav className="mt-4 space-y-3 border-l border-slate-200 pl-4 text-sm">{ACTS.map((act) => <a key={act.number} href={`#act-${act.number}`} className="block font-semibold text-slate-600 hover:text-[#0e172b]">{act.label} — {act.title}</a>)}</nav></aside>
      <article className="min-w-0"><div className="space-y-12">
        <Section id="act-01" title="ACT 1 — The Problem"><p>Agentic AI is changing the economics of enterprise software. An AI agent no longer simply receives an instruction and generates a response. It can reason, retrieve information, invoke tools, access memory, interact with other agents, apply policies, evaluate its own output, retry failed operations and ultimately take action on behalf of a user or organization.</p><Quote>The next frontier of AI assurance is not just proving that an agent works. It is proving that it works safely, reliably, efficiently and within an economically sustainable assurance envelope.</Quote>
          <Section id="s1" title="1. From Model Evaluation to System Assurance"><p>Traditional AI evaluation largely revolves around the model: input, model, response and evaluation. Agentic AI changes the system boundary. The model is now one component within a larger socio-technical system.</p><p>A production assurance programme must therefore evaluate system behaviour, not simply the generated response. Correctness, grounding, safety, security, reliability, governance, privacy and economics all become part of the assurance surface.</p></Section>
          <Section id="s2" title="2. The Agentic Harness Is an Assurance Surface"><p>The harness determines how an AI system operates around its underlying models. It controls orchestration, context, memory, tools, routing, guardrails, evaluations, retries, human intervention and observability.</p><p>Two agents using the same underlying model can behave very differently because their harnesses are different. The harness is therefore something to assure, not merely infrastructure around the model.</p></Section>
          <Section id="s3" title="3. Tokenomics Reveals the Hidden Execution"><p>For agentic systems, model cost is only one part of execution. Reasoning, planning, memory, retrieval, guardrails, evaluations, reflection, tool interactions, retries, context management and inter-agent communication can all create additional inference activity.</p><p>The important assurance question is not only “How many tokens did we consume?” but “Why did we consume them?” Token consumption becomes a signal about architecture and behaviour.</p></Section>
          <Section id="s4" title="4. Functional vs Assurance Inference"><p>Functional inference directly contributes to the business objective: understanding intent, planning, generating content, selecting actions and executing agent responsibilities.</p><p>Assurance inference supports confidence and control: guardrails, evaluations, reflection, policy interpretation, safety classification, memory validation and quality checks. A third category is waste: redundant retries, duplicate retrieval, looping or computation that does not materially improve the outcome or its assurance.</p></Section>
        </Section>

        <Section id="act-02" title="ACT 2 — The Economics of Trust"><p>Traditional FinOps asks how much an AI system costs. AI assurance adds a harder question: how much does it cost to make the system trustworthy?</p><div className="grid gap-4 sm:grid-cols-3"><Metric icon={Coins} title="Functional inference">Computation directly producing the business outcome.</Metric><Metric icon={ShieldCheck} title="Assurance inference">Computation that increases safety, quality, reliability or control.</Metric><Metric icon={Gauge} title="Assurance waste">Computation with little or no measurable assurance or business value.</Metric></div>
          <Section id="s5" title="5. The Cost of Trust"><p>Adding evaluations, memory checks and guardrails can increase execution cost while improving outcomes. The right question is therefore not whether assurance adds cost, but whether the additional assurance creates enough value or risk reduction to justify that cost.</p></Section>
          <Section id="s6" title="6. Assurance Efficiency"><p>Assurance efficiency measures how effectively an AI system converts execution resources into trustworthy outcomes.</p><CodeLine>Assurance Efficiency = Trustworthy Business Outcomes / Total AI Execution Cost</CodeLine><p>A trustworthy outcome is more than a successful response. It should satisfy the required correctness, safety, security, policy, reliability and grounding conditions.</p></Section>
          <Section id="s7" title="7. The Cheapest Agent Is Not Necessarily the Most Efficient"><p>Suppose Agent A achieves 92% business success at €0.18 per journey while Agent B achieves 97% at €0.91. Agent B is more capable, but the correct decision depends on the value of the additional 5% and the risk associated with failure.</p><p>AI economics therefore need to be evaluated alongside quality, safety, security, reliability and business value. The cheapest model is not necessarily the cheapest agent.</p></Section>
          <Section id="s8" title="8. Assurance Waste"><p>Not every additional LLM call improves assurance. Redundant evaluations, excessive context, repeated tool calls, ineffective guardrails and retries can consume inference without creating proportional value.</p><p>A mature assurance platform should distinguish necessary assurance from excessive or ineffective assurance.</p></Section>
          <Section id="s9" title="9. Every Token Should Have a Reason"><p>Every significant unit of inference should have an attributable purpose: intent classification, planning, knowledge synthesis, security evaluation, response quality evaluation or final response generation.</p><p>This makes cost explainable, but more importantly it makes behaviour explainable. Attribution turns tokenomics into assurance evidence.</p></Section>
        </Section>

        <Section id="act-03" title="ACT 3 — Evidence & Continuous Assurance"><p>Once tokenomics is connected to execution traces, it becomes part of the evidence chain. Observability tells us what happened; evaluation tells us whether it was acceptable; assurance determines whether there is enough evidence to trust the system.</p>
          <Section id="s10" title="10. Observability Becomes the Evidence Backbone"><p>A complete trace should connect the business journey to the agent, model, prompt and context, memory, retrieval, tools, guardrails, evaluations, retries, final response and business outcome. The same execution trace should support quality, security, reliability and economic analysis.</p><CodeLine>Business Journey → Agent → Model → Memory → Retrieval → Tool → Guardrail → Evaluation → Outcome → Cost</CodeLine></Section>
          <Section id="s11" title="11. Tokenomics Can Reveal Behavioural Problems"><p>A sudden increase in LLM calls per journey can indicate changed orchestration, prompt expansion, retrieval degradation, memory loops, tool failures, guardrail triggering, evaluation loops or model fallback.</p><p>Token usage can therefore become an early-warning signal for behavioural drift.</p></Section>
          <Section id="s12" title="12. Tokenomics as a Release-Gate Signal"><p>Economics can become a release-gate signal. A release might improve semantic quality and security while increasing cost per journey by 72%. Whether that is acceptable should be an explicit engineering decision rather than an accidental production discovery.</p></Section>
          <Section id="s13" title="13. A Unified Evidence Model"><p>The strongest architecture connects quality, safety, security, reliability, governance, grounding and economics through a shared execution trace and evidence graph.</p><CodeLine>Quality + Safety + Security + Reliability + Governance + Grounding + Economics → Business Outcome → Assurance Verdict</CodeLine></Section>
          <Section id="s14" title="14. From Cost per Token to Cost per Assured Business Outcome"><p>Cost per million tokens is useful for capacity planning, but the more strategic metric is cost per assured outcome.</p><CodeLine>Total AI Execution Cost / Trustworthy Business Outcomes = Cost per Assured Outcome</CodeLine><p>An architecture that spends more but produces substantially more trustworthy outcomes can be more economically efficient than a cheaper architecture.</p></Section>
          <Section id="s15" title="15. The Assurance Equation"><p>AI assurance is multi-dimensional. The objective is not to maximize one score, but to demonstrate that the AI system achieves the intended outcome within an acceptable risk and economic envelope.</p><CodeLine>Quality + Safety + Security + Reliability + Governance + Grounding + Economics → Business Outcome → Evidence → Release Trust</CodeLine></Section>
          <Section id="s16" title="16. AI Assurance Becomes Continuous"><p>Models, prompts, knowledge, retrieval, tools, policies, memory and orchestration can change independently. Assurance must therefore continue after deployment.</p><CodeLine>Deploy → Observe → Evaluate → Assure → Measure Economics → Detect Drift → Re-test → Re-assure</CodeLine></Section>
        </Section>

        <Section id="act-04" title="ACT 4 — Shyena"><p>AI Assurance Tokenomics should not become another isolated FinOps dashboard. It should be a dimension of system assurance, connected to the same execution evidence used for quality, safety, security and reliability.</p><div className="grid gap-4 sm:grid-cols-3"><Metric icon={Eye} title="Understand">Understand the system, orchestration, dependencies and execution path.</Metric><Metric icon={Workflow} title="Evaluate">Evaluate real journeys, behaviour, grounding, outcomes and efficiency.</Metric><Metric icon={ShieldCheck} title="Defend">Test security boundaries, adversarial behaviour, policy and unsafe actions.</Metric></div>
          <Section id="s17" title="17. What Shyena Changes"><p>Shyena connects system understanding, execution tracing, behavioural evaluation, security testing, economic measurement, evidence collection, business-risk assessment and release confidence into one assurance chain.</p><CodeLine>Understand → Observe → Evaluate → Defend → Measure Economics → Collect Evidence → Assure → Release</CodeLine></Section>
          <Section id="s18" title="18. The Future of Agentic AI Economics"><p>As organizations deploy multiple agents capable of performing similar tasks, agent selection can become a risk-adjusted economic decision. The best agent may not be the smartest, fastest or cheapest; it may provide the best combination of quality, safety, security, reliability, latency and cost.</p></Section>
          <Section id="s19" title="19. Toward an Assurance Score for Agentic Systems"><p>An agent assurance profile can summarize quality, grounding, security, safety, reliability, orchestration, governance, cost efficiency and assurance efficiency.</p><p>The score must never replace evidence. It is a compact representation of evidence that should remain traceable to the underlying execution.</p></Section>
        </Section>

        <Section id="act-05" title="ACT 5 — The Strategic Conclusion"><Section id="s20" title="20. The New AI Assurance Question"><p>The industry began by asking whether a model can generate a good answer. It moved to whether an agent can complete a task. The next question is whether the entire AI system can demonstrate that it achieved the intended business outcome safely, securely, reliably and within defined economic and risk boundaries.</p><Quote>Do we have sufficient evidence to trust this AI system to operate in the real world?</Quote><p>That is the purpose of AI Assurance.</p></Section></Section>

        <section className="border-y-2 border-[#0e172b] bg-[#f7f4ec] px-6 py-10 sm:px-9"><p className="font-mono text-xs uppercase tracking-[0.18em] text-[#a87900]">From tokens to trust</p><h2 className="mt-3 text-3xl font-bold tracking-tight text-[#0e172b]">The cost of intelligence is becoming the cost of assurance.</h2><p className="mt-5 max-w-3xl text-lg leading-8 text-slate-700">Every memory retrieval, evaluation, guardrail, reasoning step, tool call and retry tells part of the story. Shyena turns that execution story into evidence for trustworthy AI decisions.</p><div className="mt-8 flex flex-wrap gap-3"><Link to="/nexus" className="inline-flex items-center gap-2 bg-[#0e172b] px-5 py-3 text-sm font-semibold text-white hover:bg-slate-800">Understand with Nexus <ArrowRight className="h-4 w-4" /></Link><Link to="/vera" className="inline-flex items-center gap-2 border border-slate-300 bg-white px-5 py-3 text-sm font-semibold text-[#0e172b] hover:border-[#b4872c]">Evaluate with Vera <ArrowRight className="h-4 w-4" /></Link><Link to="/chakra" className="inline-flex items-center gap-2 border border-slate-300 bg-white px-5 py-3 text-sm font-semibold text-[#0e172b] hover:border-[#b4872c]">Defend with Chakra <ArrowRight className="h-4 w-4" /></Link></div></section>
      </div></article>
    </div></main>
  </div>;
}
