import { ArrowLeft, ArrowRight, Coins, Eye, Gauge, ShieldCheck, Workflow } from "lucide-react";
import { createFileRoute, Link } from "@tanstack/react-router";
import { DocConceptVisual } from "@/components/docs/doc-concept-visual";

const ACTS = [
  { number: "01", label: "ACT 1", title: "The Problem", items: [["1", "From Model Evaluation to System Assurance"], ["2", "The Agentic Harness Is an Assurance Surface"], ["3", "Tokenomics Reveals the Hidden Execution"], ["4", "Functional vs Assurance Inference"]] },
  { number: "02", label: "ACT 2", title: "The Economics of Trust", items: [["5", "The Cost of Trust"], ["6", "Assurance Efficiency"], ["7", "The Cheapest Agent Is Not Necessarily the Most Efficient"], ["8", "Assurance Waste"], ["9", "Every Token Should Have a Reason"]] },
  { number: "03", label: "ACT 3", title: "Evidence & Continuous Assurance", items: [["10", "Observability Becomes the Evidence Backbone"], ["11", "Tokenomics Can Reveal Behavioural Problems"], ["12", "Tokenomics as a Release-Gate Signal"], ["13", "A Unified Evidence Model"], ["14", "From Cost per Token to Cost per Assured Business Outcome"], ["15", "The Assurance Equation"], ["16", "AI Assurance Becomes Continuous"]] },
  { number: "04", label: "ACT 4", title: "Shyena", items: [["17", "What Shyena Changes"], ["18", "The Future of Agentic AI Economics"], ["19", "Toward an Assurance Score for Agentic Systems"]] },
  { number: "05", label: "ACT 5", title: "The Strategic Conclusion", items: [["20", "The New AI Assurance Question"]] },
] as const;

export const Route = createFileRoute("/docs/ai-assurance-tokenomics")({
  head: () => ({ meta: [{ title: "AI Assurance Tokenomics | Shyena Docs" }, { name: "description", content: "AI Assurance Tokenomics: connecting tokens, agent behaviour, assurance effort, value and business impact." }, { property: "og:title", content: "AI Assurance Tokenomics | Shyena Docs" }, { property: "og:description", content: "From inference to impact: connecting execution economics to continuous AI assurance." }, { property: "og:type", content: "article" }], links: [{ rel: "canonical", href: "https://www.shyena.eu/docs/ai-assurance-tokenomics" }] }),
  component: Article,
});

function Section({ id, title, children }: { id: string; title: string; children: React.ReactNode }) { return <section id={id} className="scroll-mt-28 border-t border-slate-200 pt-12 first:border-0 first:pt-0"><h2 className="text-2xl font-bold tracking-tight text-[#0e172b] sm:text-3xl">{title}</h2><div className="mt-5 space-y-5 text-[17px] leading-8 text-slate-700">{children}</div></section>; }
function Quote({ children }: { children: React.ReactNode }) { return <blockquote className="border-l-2 border-[#c89b3c] bg-[#fbf8ef] px-6 py-5 text-xl font-medium leading-8 text-[#0e172b]">{children}</blockquote>; }
function CodeLine({ children }: { children: React.ReactNode }) { return <div className="overflow-x-auto rounded-md border border-slate-200 bg-[#f7f7f5] px-5 py-4 font-mono text-sm leading-7 text-[#17233a]">{children}</div>; }
function Metric({ icon: Icon, title, children }: { icon: typeof Coins; title: string; children: React.ReactNode }) { return <div className="border border-slate-200 bg-white p-5"><Icon className="h-5 w-5 text-[#b4872c]" /><h3 className="mt-4 font-semibold text-[#0e172b]">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{children}</p></div>; }

function Article() {
  return <div className="bg-white text-slate-950">
    <section className="border-b border-slate-200 bg-[#f7f4ec]"><div className="mx-auto max-w-7xl px-5 py-8 sm:px-8"><Link to="/docs" className="inline-flex items-center gap-2 text-sm font-semibold text-slate-600 hover:text-[#0e172b]"><ArrowLeft className="h-4 w-4" /> Documentation</Link></div></section>
    <header className="border-b border-slate-200 bg-white"><div className="mx-auto max-w-6xl px-5 py-14 sm:px-8 sm:py-20"><div className="max-w-4xl"><p className="font-mono text-xs uppercase tracking-[0.22em] text-[#a87900]">AI Assurance / Economics</p><h1 className="mt-5 text-5xl font-bold leading-[1.02] tracking-[-0.045em] text-[#0e172b] sm:text-7xl">AI Assurance Tokenomics</h1><p className="mt-5 text-xl leading-8 text-slate-600 sm:text-2xl">Tokens → Behaviour → Assurance → Value → Impact</p><div className="mt-8 flex flex-wrap gap-3 text-xs font-semibold uppercase tracking-[0.14em] text-slate-500"><span className="border border-slate-300 px-3 py-2">Quality</span><span className="border border-slate-300 px-3 py-2">Safety</span><span className="border border-slate-300 px-3 py-2">Security</span><span className="border border-slate-300 px-3 py-2">Reliability</span><span className="border border-slate-300 px-3 py-2">Economics</span></div></div><div className="mt-12"><DocConceptVisual section="AI Assurance Tokenomics" /></div></div></header>
    <main className="mx-auto max-w-6xl px-5 py-14 sm:px-8 sm:py-20"><div className="grid gap-12 lg:grid-cols-[240px_minmax(0,1fr)] lg:items-start lg:gap-16"><aside className="lg:sticky lg:top-24"><p className="font-mono text-[10px] uppercase tracking-[0.18em] text-[#a87900]">On this page</p><nav className="mt-4 space-y-3 border-l border-slate-200 pl-4 text-sm">{ACTS.map((act) => <a key={act.number} href={`#act-${act.number}`} className="block font-semibold text-slate-600 hover:text-[#0e172b]">{act.label} — {act.title}</a>)}</nav></aside>
      <article className="min-w-0"><div className="mb-12 border-b border-slate-200 pb-10"><p className="max-w-4xl text-lg leading-8 text-slate-700">AI assurance economics is not simply a FinOps problem. In an agentic system, inference consumption is evidence about how the system behaves. The useful chain is <strong>Tokens → Behaviour → Assurance → Value → Impact</strong>.</p></div><div className="space-y-12">
        <Section id="act-01" title="ACT 1 — The Problem"><p>Agentic AI changes the system boundary. A model can reason, retrieve, invoke tools, access memory, interact with other agents, apply policies, evaluate its own output, retry operations and take action.</p><Quote>The assurance question is not only whether an agent works. It is whether it works safely, reliably, efficiently and within an economically sustainable assurance envelope.</Quote><Section id="s1" title="1. From Model Evaluation to System Assurance"><p>Traditional evaluation focuses on input, model, response and evaluation. Agentic systems require assurance of the larger socio-technical system: correctness, grounding, safety, security, reliability, governance, privacy and economics.</p></Section><Section id="s2" title="2. The Agentic Harness Is an Assurance Surface"><p>The harness controls orchestration, context, memory, tools, routing, guardrails, evaluations, retries, human intervention and observability. Two agents using the same model can behave differently because their harnesses differ.</p></Section><Section id="s3" title="3. Tokenomics Reveals the Hidden Execution"><p>Reasoning, planning, memory, retrieval, guardrails, evaluations, reflection, tool interactions, retries, context management and inter-agent communication can all create inference activity.</p><p>The key question is not only “How many tokens?” but “Why were they consumed?”</p></Section><Section id="s4" title="4. Functional vs Assurance Inference"><p>Functional inference directly contributes to the business objective. Assurance inference supports confidence and control. Waste includes redundant retries, duplicate retrieval, looping or computation that creates little additional value.</p></Section></Section>
        <Section id="act-02" title="ACT 2 — The Economics of Trust"><p>Traditional FinOps asks how much an AI system costs. AI assurance adds: how much does it cost to make the system trustworthy?</p><div className="grid gap-4 sm:grid-cols-3"><Metric icon={Coins} title="Tokens">Inference consumption attributable to an execution purpose.</Metric><Metric icon={ShieldCheck} title="Assurance">Inference and controls that increase quality, safety, security or reliability.</Metric><Metric icon={Gauge} title="Value">The business outcome and risk reduction produced by the total execution.</Metric></div><Section id="s5" title="5. The Cost of Trust"><p>Additional evaluation and control can increase execution cost while improving outcomes. The relevant decision is whether the incremental assurance value justifies the incremental cost and risk reduction.</p></Section><Section id="s6" title="6. Assurance Efficiency"><p>Assurance efficiency measures how effectively execution resources become trustworthy outcomes.</p><CodeLine>Assurance Efficiency = Trustworthy Business Outcomes / Total AI Execution Cost</CodeLine></Section><Section id="s7" title="7. The Cheapest Agent Is Not Necessarily the Most Efficient"><p>A cheaper agent can be less efficient if it produces materially more failures, remediation, unsafe actions or untrusted outcomes. Agent selection should therefore consider quality, safety, security, reliability and business value alongside cost.</p></Section><Section id="s8" title="8. Assurance Waste"><p>Redundant evaluations, excessive context, repeated tool calls, ineffective guardrails and retries can consume inference without proportional assurance value.</p></Section><Section id="s9" title="9. Every Token Should Have a Reason"><p>Significant inference should have an attributable purpose such as planning, retrieval, synthesis, security evaluation, quality evaluation or response generation. Attribution makes cost and behaviour explainable.</p></Section></Section>
        <Section id="act-03" title="ACT 3 — Evidence & Continuous Assurance"><p>When tokenomics is connected to execution traces, it becomes part of the evidence chain.</p><Section id="s10" title="10. Observability Becomes the Evidence Backbone"><p>A complete trace should connect the business journey to the agent, model, context, memory, retrieval, tools, guardrails, evaluations, retries, response and outcome.</p><CodeLine>Business Journey → Agent → Model → Memory → Retrieval → Tool → Guardrail → Evaluation → Outcome → Cost</CodeLine></Section><Section id="s11" title="11. Tokenomics Can Reveal Behavioural Problems"><p>A sudden increase in calls or tokens per journey can indicate orchestration changes, prompt expansion, retrieval degradation, memory loops, tool failures, guardrail triggering, evaluation loops or model fallback.</p></Section><Section id="s12" title="12. Tokenomics as a Release-Gate Signal"><p>Economic regression can be an explicit release signal. A release that improves quality while materially increasing cost per assured journey should trigger an engineering decision, not an accidental production discovery.</p></Section><Section id="s13" title="13. A Unified Evidence Model"><p>Quality, safety, security, reliability, governance, grounding and economics should connect through a shared execution trace and evidence graph.</p><CodeLine>Quality + Safety + Security + Reliability + Governance + Grounding + Economics → Business Outcome → Assurance Verdict</CodeLine></Section><Section id="s14" title="14. From Cost per Token to Cost per Assured Business Outcome"><p>The strategic metric is cost per trustworthy outcome, not token price alone.</p><CodeLine>Total AI Execution Cost / Trustworthy Business Outcomes = Cost per Assured Outcome</CodeLine></Section><Section id="s15" title="15. The Assurance Equation"><p>The objective is not to maximize one score. It is to demonstrate that the system achieves the intended outcome within an acceptable risk and economic envelope.</p><CodeLine>Quality + Safety + Security + Reliability + Governance + Grounding + Economics → Business Outcome → Evidence → Release Trust</CodeLine></Section><Section id="s16" title="16. AI Assurance Becomes Continuous"><p>Models, prompts, knowledge, retrieval, tools, policies, memory and orchestration can change independently. Assurance must therefore continue after deployment.</p><CodeLine>Deploy → Observe → Evaluate → Assure → Measure Economics → Detect Drift → Re-test → Re-assure</CodeLine></Section></Section>
        <Section id="act-04" title="ACT 4 — Shyena"><p>Tokenomics is an assurance dimension, not an isolated cost dashboard. It connects execution economics to the same evidence used for quality, safety, security and reliability.</p><div className="grid gap-4 sm:grid-cols-3"><Metric icon={Eye} title="Understand">Understand system structure, dependencies and execution path.</Metric><Metric icon={Workflow} title="Evaluate">Evaluate real journeys, behaviour, outcomes and efficiency.</Metric icon={ShieldCheck} title="Defend">Test security boundaries, policy and unsafe actions.</Metric></div><Section id="s17" title="17. What Shyena Changes"><p>Shyena connects system understanding, execution tracing, behavioural evaluation, security testing, economic measurement, evidence collection and release confidence into one assurance chain.</p><CodeLine>Understand → Observe → Evaluate → Defend → Measure Economics → Collect Evidence → Assure → Release</CodeLine></Section><Section id="s18" title="18. The Future of Agentic AI Economics"><p>As organizations deploy multiple agents capable of similar work, agent selection becomes a risk-adjusted economic decision. The best agent is the one that produces the required trustworthy outcome within the acceptable assurance envelope.</p></Section><Section id="s19" title="19. Toward an Assurance Score for Agentic Systems"><p>An assurance score should be multidimensional and evidence-backed. Economics should contribute to the decision without allowing low cost to mask critical quality, security or integrity failures.</p></Section></Section>
        <Section id="act-05" title="ACT 5 — The Strategic Conclusion"><Section id="s20" title="20. The New AI Assurance Question"><p>The strategic question changes from “How much does this AI cost?” to “What does it cost to produce a trustworthy business outcome, and what evidence proves that outcome is worth the cost and risk?”</p><Quote>Tokens are an execution signal. Behaviour gives them meaning. Assurance determines whether the behaviour can be trusted. Value determines whether the trust is worth buying. Impact determines whether the system matters.</Quote></Section></Section>
      </div></article></div></main>
  </div>;
}
