import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowRight, Check, ChevronRight, ShieldCheck, Sparkles } from "lucide-react";

export const Route = createFileRoute("/")({
  head: () => ({
    meta: [
      { title: "Shyena | AI Agent Testing, Evaluation & Security" },
      { name: "description", content: "Test, evaluate and secure AI agents with realistic simulations, trace evidence and release-ready assurance." },
      { property: "og:title", content: "Shyena | AI Agent Testing, Evaluation & Security" },
      { property: "og:description", content: "Realistic AI agent testing, evaluation and security with evidence-backed release decisions." },
      { property: "og:type", content: "website" },
      { property: "og:url", content: "https://www.shyena.eu/" },
    ],
  }),
  component: HomePage,
});

const platform = [
  ["NEXUS", "Understand your AI system", "Map flows, orchestration, tools, dependencies and business-critical journeys before you test.", "/nexus"],
  ["VERA", "Test and evaluate", "Simulate realistic users, run multi-turn journeys and evaluate outcomes, semantics and execution integrity.", "/vera"],
  ["CHAKRA", "Secure your agents", "Red-team prompts, tools, trust boundaries and unsafe execution paths before production.", "/chakra"],
] as const;

const evaluation = [
  ["Deterministic", "Facts your system must satisfy: APIs, business rules, states, routes and tool contracts."],
  ["Semantic", "Judge relevance, correctness, tone and business meaning across responses and conversations."],
  ["Orchestrator", "Verify that the agent selected the right intent, route, tool and next action."],
  ["Security", "Detect prompt injection, policy breaks, unsafe tool calls and trust-boundary failures."],
] as const;

const integrations = ["Cognigy", "Agentforce", "LangGraph", "LangChain", "CrewAI", "RAG", "AWS Bedrock", "Azure OpenAI", "Playwright", "OpenTelemetry", "GitHub Actions", "GitLab CI"];

function HomePage() {
  return (
    <main className="min-h-screen bg-white text-[#17233f]">
      <section className="border-b border-[#e9e9e9] bg-white">
        <div className="mx-auto max-w-[1280px] px-5 pb-20 pt-20 sm:px-8 lg:px-10 lg:pb-28 lg:pt-28">
          <div className="mx-auto max-w-[1050px] text-center">
            <div className="inline-flex items-center rounded-full border border-[#f1d6bf] bg-[#fff8f2] px-3.5 py-1.5 text-[12px] font-semibold text-[#d96900]">AI quality engineering for production agents</div>
            <h1 className="mt-7 font-[Sora] text-[clamp(3.2rem,7vw,6.8rem)] font-extrabold leading-[.95] tracking-[-.065em] text-[#17233f]">Make complex AI agents<br /><span className="text-[#e87512]">reliable in production.</span></h1>
            <p className="mx-auto mt-7 max-w-[760px] text-[19px] leading-8 text-[#5d6470] sm:text-[21px]">Simulation-based testing, evaluation and security that shows what your agent did, why it failed and whether it is ready to ship.</p>
            <div className="mt-9 flex flex-wrap justify-center gap-3"><Link to="/contact" className="inline-flex h-12 items-center gap-2 rounded-md bg-[#e87512] px-6 text-sm font-semibold text-white transition hover:bg-[#d96900]">Book a demo <ArrowRight className="h-4 w-4" /></Link><Link to="/ai-agent-testing" className="inline-flex h-12 items-center gap-2 rounded-md border border-[#d8dce3] bg-white px-6 text-sm font-semibold text-[#17233f] transition hover:border-[#17233f]">Explore agent testing <ArrowRight className="h-4 w-4" /></Link></div>
          </div>
          <div className="mx-auto mt-16 max-w-[1040px] overflow-hidden rounded-xl border border-[#dedfe3] bg-[#fbfbfb] shadow-[0_25px_70px_-45px_rgba(23,35,63,.35)]">
            <div className="flex items-center gap-2 border-b border-[#e7e7e7] bg-white px-5 py-3"><span className="h-2.5 w-2.5 rounded-full bg-[#d1d5db]" /><span className="h-2.5 w-2.5 rounded-full bg-[#d1d5db]" /><span className="h-2.5 w-2.5 rounded-full bg-[#d1d5db]" /><span className="ml-3 font-mono text-[10px] uppercase tracking-[.16em] text-[#9ca3af]">Shyena · agent assurance workspace</span></div>
            <div className="grid gap-0 md:grid-cols-[1fr_1.25fr]">
              <div className="border-b border-[#e8e8e8] bg-white p-6 text-left md:border-b-0 md:border-r sm:p-8"><div className="font-mono text-[10px] uppercase tracking-[.18em] text-[#e87512]">Simulation</div><div className="mt-4 text-xl font-bold text-[#17233f]">Change customer address</div><div className="mt-5 space-y-2">{["Customer asks for address change", "Agent identifies account", "Identity verification", "Update address", "Confirmation"].map((step, i) => <div key={step} className="flex items-center gap-3 rounded-md border border-[#ececec] bg-[#fafafa] px-3 py-2.5 text-sm text-[#4b5563]"><span className="flex h-5 w-5 shrink-0 items-center justify-center rounded-full bg-[#fff1e6] text-[10px] font-bold text-[#e87512]">{i + 1}</span>{step}</div>)}</div></div>
              <div className="bg-[#fbfbfb] p-6 text-left sm:p-8"><div className="flex items-center justify-between"><div><div className="font-mono text-[10px] uppercase tracking-[.18em] text-[#9ca3af]">Evaluation</div><div className="mt-2 text-lg font-bold text-[#17233f]">Execution evidence</div></div><span className="rounded-full bg-[#fff3e8] px-3 py-1 text-[11px] font-bold text-[#d96900]">REVIEW</span></div><div className="mt-6 grid gap-2 sm:grid-cols-2">{[["Journey", "17 / 17", "PASS"], ["Business rules", "14 / 15", "FINDING"], ["Semantic quality", "0.91", "SCORED"], ["Tool execution", "Complete", "PASS"], ["Security", "No critical", "PASS"], ["Trace evidence", "Linked", "VERIFIED"]].map(([label, value, state]) => <div key={label} className="rounded-md border border-[#e5e5e5] bg-white p-3.5"><div className="text-xs font-semibold text-[#6b7280]">{label}</div><div className="mt-1 text-lg font-bold text-[#17233f]">{value}</div><div className="mt-1 font-mono text-[9px] uppercase tracking-[.12em] text-[#9ca3af]">{state}</div></div>)}</div><div className="mt-5 flex items-center gap-2 border-t border-[#e5e5e5] pt-5 text-xs text-[#667085]"><ShieldCheck className="h-4 w-4 text-[#e87512]" /> Every finding remains linked to execution evidence.</div></div>
            </div>
          </div>
        </div>
      </section>

      <section className="border-b border-[#e9e9e9] bg-[#fafafa]"><div className="mx-auto max-w-[1280px] px-5 py-12 sm:px-8 lg:px-10"><div className="grid gap-8 md:grid-cols-3"><div><div className="text-sm font-bold text-[#17233f]">Realistic simulations</div><p className="mt-2 text-sm leading-6 text-[#69707d]">Push agents through multi-turn journeys instead of checking isolated answers.</p></div><div><div className="text-sm font-bold text-[#17233f]">Evidence, not just scores</div><p className="mt-2 text-sm leading-6 text-[#69707d]">Trace the route, tool calls, business rules and evaluation behind every finding.</p></div><div><div className="text-sm font-bold text-[#17233f]">Release assurance</div><p className="mt-2 text-sm leading-6 text-[#69707d]">Turn test, evaluation and security evidence into a governed release decision.</p></div></div></div></section>

      <section className="bg-white"><div className="mx-auto max-w-[1280px] px-5 py-20 sm:px-8 lg:px-10 lg:py-24"><div className="max-w-3xl"><div className="text-sm font-semibold text-[#e87512]">The problem</div><h2 className="mt-4 font-[Sora] text-[clamp(2.4rem,5vw,4.6rem)] font-extrabold leading-[.98] tracking-[-.055em] text-[#17233f]">AI agents can look right<br />while doing the wrong thing.</h2><p className="mt-6 max-w-2xl text-lg leading-8 text-[#626976]">A generated answer is only one signal. Production agents make decisions, call tools, change state, follow policies and coordinate multiple systems.</p></div><div className="mt-12 grid gap-px overflow-hidden rounded-lg border border-[#e2e4e8] bg-[#e2e4e8] sm:grid-cols-2 lg:grid-cols-4">{[["Wrong route", "The response looks correct but the agent selected the wrong intent or workflow."],["Wrong tool", "The agent called the wrong API, used the wrong arguments or skipped a required action."],["Broken journey", "A conversation passes individual checks but fails to complete the customer's goal."],["Unsafe path", "A seemingly helpful interaction crosses a policy, security or trust boundary."]].map(([title,text],i)=><div key={title} className="bg-white p-7"><div className="font-mono text-[10px] font-semibold text-[#e87512]">0{i+1}</div><h3 className="mt-8 text-lg font-bold text-[#17233f]">{title}</h3><p className="mt-2 text-sm leading-6 text-[#69707d]">{text}</p></div>)}</div></div></section>

      <section className="border-y border-[#e8e8e8] bg-[#fafafa]"><div className="mx-auto max-w-[1280px] px-5 py-20 sm:px-8 lg:px-10 lg:py-24"><div className="flex flex-col justify-between gap-8 md:flex-row md:items-end"><div><div className="text-sm font-semibold text-[#e87512]">Platform</div><h2 className="mt-4 font-[Sora] text-[clamp(2.5rem,5vw,4.5rem)] font-extrabold leading-[.98] tracking-[-.055em] text-[#17233f]">One platform for the<br />whole assurance loop.</h2></div><p className="max-w-md text-base leading-7 text-[#69707d]">Understand the system, test realistic behaviour, evaluate outcomes and secure the paths that matter.</p></div><div className="mt-12 grid gap-4 lg:grid-cols-3">{platform.map(([name,title,text,href],i)=><Link key={name} to={href} className="group rounded-xl border border-[#dedfe3] bg-white p-7 transition hover:-translate-y-1 hover:border-[#c8cbd1] hover:shadow-[0_20px_50px_-35px_rgba(23,35,63,.4)] lg:p-8"><div className="flex items-center justify-between"><span className="font-mono text-[10px] font-bold tracking-[.18em] text-[#e87512]">0{i+1} · {name}</span><ChevronRight className="h-4 w-4 text-[#9ca3af] transition group-hover:translate-x-1 group-hover:text-[#e87512]" /></div><h3 className="mt-12 font-[Sora] text-2xl font-bold tracking-[-.035em] text-[#17233f]">{title}</h3><p className="mt-4 text-sm leading-7 text-[#69707d]">{text}</p><div className="mt-7 text-xs font-semibold text-[#e87512]">Explore {name} <ArrowRight className="ml-1 inline h-3.5 w-3.5" /></div></Link>)}</div></div></section>

      <section className="bg-white"><div className="mx-auto max-w-[1280px] px-5 py-20 sm:px-8 lg:px-10 lg:py-24"><div className="max-w-3xl"><div className="text-sm font-semibold text-[#e87512]">Evaluate</div><h2 className="mt-4 font-[Sora] text-[clamp(2.5rem,5vw,4.5rem)] font-extrabold leading-[.98] tracking-[-.055em] text-[#17233f]">Score the whole journey,<br />not just the final answer.</h2><p className="mt-6 max-w-2xl text-lg leading-8 text-[#626976]">Combine hard system facts with semantic judgement and execution evidence. Each signal answers a different quality question.</p></div><div className="mt-12 grid gap-4 md:grid-cols-2">{evaluation.map(([title,text],i)=><div key={title} className="rounded-lg border border-[#e1e3e7] p-6 sm:p-7"><div className="flex items-center gap-3"><span className="flex h-8 w-8 items-center justify-center rounded-full bg-[#fff2e8] text-xs font-bold text-[#e87512]">{i+1}</span><h3 className="text-lg font-bold text-[#17233f]">{title}</h3></div><p className="mt-4 pl-11 text-sm leading-7 text-[#69707d]">{text}</p></div>)}</div></div></section>

      <section className="border-y border-[#e8e8e8] bg-[#fafafa]"><div className="mx-auto max-w-[1280px] px-5 py-20 sm:px-8 lg:px-10 lg:py-24"><div className="grid gap-12 lg:grid-cols-[.8fr_1.2fr] lg:items-start"><div><div className="text-sm font-semibold text-[#e87512]">Autonomous testing</div><h2 className="mt-4 font-[Sora] text-[clamp(2.5rem,5vw,4.3rem)] font-extrabold leading-[.98] tracking-[-.055em] text-[#17233f]">Let your AI test your AI.</h2><p className="mt-6 text-lg leading-8 text-[#626976]">Start with a business goal. Shyena turns it into executable test intent, runs the journey, evaluates the trace and preserves the evidence.</p></div><div className="grid gap-3">{[["01","Goal","Describe the outcome in plain language."],["02","Plan","Generate realistic scenarios and assertions."],["03","Run","Execute conversations and agent actions."],["04","Judge","Evaluate behaviour and execution integrity."],["05","Prove","Create release evidence and a decision."]].map(([n,t,d])=><div key={n} className="flex gap-5 rounded-lg border border-[#e1e3e7] bg-white p-5"><span className="font-mono text-[10px] font-semibold text-[#e87512]">{n}</span><div><div className="font-semibold text-[#17233f]">{t}</div><div className="mt-1 text-sm text-[#69707d]">{d}</div></div><Check className="ml-auto h-4 w-4 shrink-0 text-[#c5c9d0]" /></div>)}</div></div></div></section>

      <section className="bg-white"><div className="mx-auto max-w-[1280px] px-5 py-20 sm:px-8 lg:px-10 lg:py-24"><div className="flex flex-col justify-between gap-8 md:flex-row md:items-end"><div><div className="text-sm font-semibold text-[#e87512]">Integrations</div><h2 className="mt-4 font-[Sora] text-[clamp(2.4rem,4.5vw,4rem)] font-extrabold leading-[.98] tracking-[-.05em] text-[#17233f]">Works with your existing stack.</h2></div><Link to="/docs" className="text-sm font-semibold text-[#17233f]">View documentation <ArrowRight className="ml-1 inline h-4 w-4" /></Link></div><div className="mt-10 flex flex-wrap gap-2">{integrations.map((item)=><span key={item} className="rounded-md border border-[#e0e2e6] bg-[#fafafa] px-4 py-2.5 text-sm font-medium text-[#5f6672]">{item}</span>)}</div></div></section>

      <section className="bg-[#17233f] text-white"><div className="mx-auto max-w-[1280px] px-5 py-20 sm:px-8 lg:px-10 lg:py-24"><div className="grid gap-10 lg:grid-cols-[1fr_auto] lg:items-end"><div><div className="text-sm font-semibold text-[#f59a4b]">Production readiness</div><h2 className="mt-4 max-w-4xl font-[Sora] text-[clamp(2.6rem,5vw,5rem)] font-extrabold leading-[.98] tracking-[-.055em]">Know what happened.<br />Know whether to ship.</h2><p className="mt-6 max-w-2xl text-lg leading-8 text-white/65">Bring one critical AI journey. Shyena shows how it can be tested, evaluated, secured and connected to release evidence.</p></div><Link to="/contact" className="inline-flex h-12 items-center gap-2 rounded-md bg-[#e87512] px-6 text-sm font-semibold text-white transition hover:bg-[#f18a32]">Book a demo <ArrowRight className="h-4 w-4" /></Link></div></div></section>
    </main>
  );
}
