import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowRight, Check, HelpCircle, GraduationCap, Rocket, Code2, Puzzle, Gauge, ShieldCheck } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion";
import { CtaBand } from "@/components/site/cta-band";
import { Reveal } from "@/components/site/reveal";

export const Route = createFileRoute("/pricing")({
  head: () => ({
    meta: [
      { title: "Pricing — Shyena AI Agent Assurance Platform" },
      { name: "description", content: "Clear SaaS pricing for Shyena AI agent assurance. Foundation €12,000/year, Scale €30,000/year, and Enterprise from €60,000/year, with defined assurance and security volumes. Professional services are separate." },
      { property: "og:title", content: "Pricing — Shyena AI Agent Assurance Platform" },
      { property: "og:description", content: "Transparent annual SaaS pricing with defined assurance and security consumption. No per-user or per-agent licensing." },
    ],
    links: [{ rel: "canonical", href: "https://shyena.eu/pricing" }],
  }),
  component: PricingPage,
});

const PLANS = [
  {
    name: "Foundation",
    label: "€12,000 / year",
    description: "For one production assurance program and teams establishing repeatable AI agent testing.",
    volume: "100 assurance journeys + 25 security runs / month",
    overage: "€100 / additional 100 assurance journeys · €150 / additional 25 security runs",
    features: ["Nexus + Vera + Chakra", "1 production tenant", "Unlimited platform users", "Unlimited agents and projects within the contracted volume", "100 assurance journeys per month", "25 security runs per month", "7-day evidence retention", "CI/CD and API access", "Standard support"],
  },
  {
    name: "Scale",
    label: "€30,000 / year",
    description: "For growing AI portfolios running assurance across multiple agents, environments and release pipelines.",
    volume: "500 assurance journeys + 100 security runs / month",
    overage: "€75 / additional 100 assurance journeys · €120 / additional 25 security runs",
    features: ["Nexus + Vera + Chakra", "Up to 3 production environments", "Unlimited platform users", "Unlimited agents and projects within the contracted volume", "500 assurance journeys per month", "100 security runs per month", "30-day evidence retention", "SSO / RBAC and usage reporting", "CI/CD and API access", "Priority support"],
    featured: true,
  },
  {
    name: "Enterprise",
    label: "From €60,000 / year",
    description: "For governed enterprise deployment with custom volumes, security requirements and operating models.",
    volume: "Custom assurance + security consumption",
    overage: "Custom contracted volume and overage terms",
    features: ["Nexus + Vera + Chakra", "Custom production environments and tenant model", "Unlimited platform users", "Custom assurance and security volumes", "90-day or negotiated evidence retention", "Enterprise identity and governance", "Custom data and deployment controls", "SLA and escalation model", "Security and procurement support", "Private-cloud options where required"],
  },
] as const;

const COMMERCIAL_UNITS = [
  { icon: Gauge, title: "Assurance journey", body: "One executed customer or business journey, including the conversation, evaluation and evidence generated by that run." },
  { icon: ShieldCheck, title: "Security run", body: "One contracted adversarial security execution against an agent or defined security target." },
  { icon: ArrowRight, title: "Predictable overage", body: "Published plans define an overage rate for additional consumption. Enterprise customers negotiate volume and commercial terms before signing." },
] as const;

const SERVICES = [
  { icon: Rocket, title: "Pilot / proof of value", body: "A scoped engagement against your environment. Priced separately from the recurring SaaS subscription." },
  { icon: GraduationCap, title: "Training and enablement", body: "Workshops, onboarding and team enablement are professional services and are quoted separately." },
  { icon: Code2, title: "Custom development", body: "Bespoke workflows, evaluators, reporting and engineering work are scoped and priced separately." },
  { icon: Puzzle, title: "Framework adapters", body: "New agent frameworks, channels and platform integrations are separately scoped rather than promised as unlimited platform features." },
];

const FAQS = [
  ["Are the prices real list prices?", "Yes. Foundation is €12,000 per year and Scale is €30,000 per year. Enterprise starts from €60,000 per year because deployment, governance, retention, security and consumption requirements vary materially. Prices are annual SaaS subscription prices and exclude VAT."],
  ["What does an assurance journey mean?", "An assurance journey is one executed customer or business journey, including the conversation, evaluation and evidence produced by that execution. Monthly included volumes are measured against executed journeys, not the number of users or agents in the platform."],
  ["Are users and agents charged separately?", "No. Shyena does not use per-user or per-agent licensing in these plans. Users, agents and projects can scale within the contracted assurance and security consumption."],
  ["What happens when we exceed the included volume?", "Foundation and Scale publish an overage rate so customers know the commercial exposure before they buy. Enterprise volume and overage terms are agreed in the order form before deployment."],
  ["What is not included in the SaaS price?", "Pilots, training, custom development and bespoke framework or platform adapters are separate professional services. They are scoped and priced explicitly rather than hidden inside the software subscription."],
  ["Can the commercial terms be negotiated?", "Yes. The public prices provide a clear starting point. Enterprise customers can negotiate committed volume, deployment model, support, retention, security requirements and other commercial terms at contract stage."],
];

function PricingPage() {
  return <>
    <section className="relative overflow-hidden bg-slate-950 text-white">
      <div className="absolute inset-0 opacity-20 [background-image:linear-gradient(rgba(148,163,184,.08)_1px,transparent_1px),linear-gradient(90deg,rgba(148,163,184,.08)_1px,transparent_1px)] [background-size:56px_56px]" />
      <div className="relative mx-auto w-full max-w-7xl px-5 pb-16 pt-20 sm:px-8 sm:pt-28">
        <div className="mx-auto max-w-4xl text-center">
          <span className="inline-flex items-center gap-2 rounded-full border border-slate-700 bg-white/5 px-3.5 py-1.5 text-xs font-medium text-slate-300"><HelpCircle className="h-3.5 w-3.5 text-violet-300" />Public SaaS pricing</span>
          <h1 className="mt-6 text-5xl font-bold leading-[1.05] tracking-tight sm:text-7xl">Clear pricing for AI assurance that scales.</h1>
          <p className="mx-auto mt-6 max-w-3xl text-lg leading-relaxed text-slate-300">Start with a published annual platform price. Your plan includes a defined monthly assurance and security volume, with predictable overage terms. No per-user or per-agent licensing.</p>
          <p className="mt-4 text-sm text-slate-400">All prices are annual, exclude VAT and are subject to the applicable order form.</p>
        </div>
      </div>
    </section>

    <section className="mx-auto w-full max-w-7xl px-5 py-16 sm:px-8 sm:py-20">
      <div className="mx-auto max-w-3xl text-center"><p className="font-mono text-xs uppercase tracking-[0.18em] text-violet-600">Choose your starting point</p><h2 className="mt-4 text-3xl font-bold tracking-tight text-slate-950 sm:text-4xl">Know the price before the conversation starts.</h2><p className="mt-4 text-slate-600">The public plan defines the software commitment. Enterprise negotiation happens around volume, deployment and governance—not around hiding the starting price.</p></div>
      <div className="mt-12 grid gap-5 lg:grid-cols-3">
        {PLANS.map((plan) => <div key={plan.name} className={`relative flex h-full flex-col rounded-3xl border bg-white p-7 ${plan.featured ? "border-violet-400 shadow-2xl ring-1 ring-violet-200" : "border-slate-200 shadow-sm"}`}>
          {plan.featured && <span className="absolute right-6 top-6 rounded-full bg-violet-100 px-3 py-1 text-xs font-semibold text-violet-700">Most popular</span>}
          <p className="text-sm font-semibold uppercase tracking-[0.18em] text-violet-600">{plan.name}</p>
          <h3 className="mt-3 text-3xl font-bold tracking-tight text-slate-950">{plan.label}</h3>
          <p className="mt-3 min-h-16 text-sm leading-relaxed text-slate-600">{plan.description}</p>
          <div className="mt-6 rounded-2xl border border-slate-200 bg-slate-50 p-4"><p className="text-xs font-semibold uppercase tracking-wider text-slate-500">Included monthly volume</p><p className="mt-1 font-semibold text-slate-900">{plan.volume}</p></div>
          <div className="mt-3 rounded-2xl border border-violet-100 bg-violet-50/50 p-4"><p className="text-xs font-semibold uppercase tracking-wider text-slate-500">Overage</p><p className="mt-1 text-sm font-medium text-slate-800">{plan.overage}</p></div>
          <ul className="mt-6 flex-1 space-y-3 border-t border-slate-200 pt-6">{plan.features.map((feature) => <li key={feature} className="flex items-start gap-3 text-sm text-slate-700"><span className="mt-0.5 inline-flex h-5 w-5 shrink-0 items-center justify-center rounded-full bg-violet-100 text-violet-700"><Check className="h-3 w-3" /></span>{feature}</li>)}</ul>
          <Button asChild className="mt-8" variant={plan.featured ? "default" : "outline"}><Link to="/contact">Choose {plan.name} <ArrowRight className="h-4 w-4" /></Link></Button>
        </div>)}
      </div>
    </section>

    <section className="bg-slate-50"><div className="mx-auto max-w-7xl px-5 py-20 sm:px-8 sm:py-24"><Reveal><div className="max-w-3xl"><span className="font-mono text-xs uppercase tracking-[0.18em] text-violet-600">How consumption works</span><h2 className="mt-4 text-3xl font-bold text-slate-950 sm:text-4xl">Meter the assurance work, not the people.</h2><p className="mt-4 text-slate-600">The commercial model avoids per-seat and per-agent taxes. It follows the assurance activity that creates infrastructure and evaluation cost.</p></div></Reveal><div className="mt-10 grid gap-5 md:grid-cols-3">{COMMERCIAL_UNITS.map(({ icon: Icon, title, body }) => <div key={title} className="rounded-2xl border border-slate-200 bg-white p-6"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-violet-100 text-violet-700"><Icon className="h-5 w-5" /></div><h3 className="mt-5 font-semibold text-slate-950">{title}</h3><p className="mt-2 text-sm leading-relaxed text-slate-600">{body}</p></div>)}</div></div></section>

    <section className="mx-auto max-w-7xl px-5 py-20 sm:px-8 sm:py-24"><Reveal><div className="max-w-3xl"><span className="font-mono text-xs uppercase tracking-[0.18em] text-violet-600">Platform included</span><h2 className="mt-4 text-3xl font-bold text-slate-950 sm:text-4xl">Nexus + Vera + Chakra in every plan.</h2><p className="mt-4 text-slate-600">The plans are commercial tiers of one Shyena assurance platform. The difference is primarily contracted volume, environment scale and enterprise governance.</p></Reveal><div className="mt-10 grid gap-5 md:grid-cols-3"><div className="rounded-2xl border border-slate-200 p-6"><p className="text-xs font-semibold uppercase tracking-widest text-violet-600">Understand</p><h3 className="mt-2 text-xl font-bold">Nexus</h3><p className="mt-2 text-sm leading-relaxed text-slate-600">System-map intelligence for understanding agent structure and generating assurance candidates.</p></div><div className="rounded-2xl border border-slate-200 p-6"><p className="text-xs font-semibold uppercase tracking-widest text-violet-600">Evaluate</p><h3 className="mt-2 text-xl font-bold">Vera</h3><p className="mt-2 text-sm leading-relaxed text-slate-600">Agentic quality evaluation across real conversations, deterministic contracts, semantic judgment and execution integrity.</p></div><div className="rounded-2xl border border-slate-200 p-6"><p className="text-xs font-semibold uppercase tracking-widest text-violet-600">Defend</p><h3 className="mt-2 text-xl font-bold">Chakra</h3><p className="mt-2 text-sm leading-relaxed text-slate-600">Adversarial assurance for agentic systems, with attack execution and security release controls.</p></div></div></section>

    <section className="bg-slate-950 py-20 text-white"><div className="mx-auto max-w-7xl px-5 sm:px-8"><div className="max-w-3xl"><p className="font-mono text-xs uppercase tracking-[0.18em] text-violet-300">Separate professional services</p><h2 className="mt-4 text-3xl font-bold sm:text-4xl">No hidden implementation promises.</h2><p className="mt-4 text-slate-300">The SaaS price is for the platform. Specialist engineering and enablement are scoped separately so neither the customer nor Shyena is committed to an undefined bundle of work.</p></div><div className="mt-10 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{SERVICES.map(({ icon: Icon, title, body }) => <div key={title} className="rounded-2xl border border-slate-700 bg-white/[0.03] p-6"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-violet-500/20 text-violet-300"><Icon className="h-5 w-5" /></div><h3 className="mt-5 font-semibold">{title}</h3><p className="mt-2 text-sm leading-relaxed text-slate-400">{body}</p></div>)}</div></div></section>

    <section className="mx-auto w-full max-w-7xl px-5 py-20 sm:px-8"><div className="max-w-3xl"><p className="font-mono text-xs uppercase tracking-[0.18em] text-violet-600">Commercial guardrails</p><h2 className="mt-4 text-3xl font-bold text-slate-950 sm:text-4xl">The public price is the starting point. The contract defines the final scope.</h2><p className="mt-4 text-slate-600">Negotiation belongs at the contract stage: committed volumes, deployment model, support, retention, security requirements, data controls and enterprise discounts can be agreed before signing. The website does not promise unlimited engineering, unlimited security activity or unlimited integrations.</p></div><div className="mt-8 flex flex-wrap gap-3"><Button asChild><Link to="/contact">Discuss your requirements <ArrowRight className="h-4 w-4" /></Link></Button></div></section>

    <section className="mx-auto w-full max-w-7xl px-5 py-8 sm:px-8 sm:py-16"><div className="max-w-3xl"><p className="font-mono text-xs uppercase tracking-[0.18em] text-violet-600">FAQ</p><h2 className="mt-4 text-3xl font-bold text-slate-950 sm:text-4xl">Pricing and commercial model</h2></div><div className="mt-8 max-w-3xl"><Accordion type="single" collapsible>{FAQS.map(([q, a], i) => <AccordionItem key={q} value={`item-${i}`}><AccordionTrigger className="text-left">{q}</AccordionTrigger><AccordionContent className="leading-relaxed text-slate-600">{a}</AccordionContent></AccordionItem>)}</Accordion></div></section>
    <CtaBand />
  </>;
}
