import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowRight, Download } from "lucide-react";

const SITE="https://www.shyena.eu";
export const Route=createFileRoute("/sample-report")({head:()=>({links:[{rel:"canonical",href:SITE+"/sample-report"}],meta:[
{title:"Sample Release Assurance Report | Shyena"},
{name:"description",content:"Synthetic sample release assurance report showing evaluation, security findings, governance evidence and a release verdict."},
{property:"og:title",content:"Sample Release Assurance Report | Shyena"},
{property:"og:description",content:"Synthetic sample release assurance report from Shyena."},
{property:"og:url",content:SITE+"/sample-report"}
]}),component:Page});

function Page(){return <main className="bg-[#f7f8fa] text-[#17213f]">
<section className="bg-[#07101f] text-white"><div className="mx-auto max-w-[1200px] px-5 py-20 sm:px-8 lg:px-10 lg:py-24"><div className="max-w-4xl"><div className="font-mono text-[10px] font-bold uppercase tracking-[.2em] text-[#f18a32]">Sample report · Illustrative</div><h1 className="mt-5 font-[Sora] text-[clamp(3rem,6vw,5.5rem)] font-extrabold leading-[.92] tracking-[-.06em]">Know whether to ship, and prove why.</h1><p className="mt-7 max-w-3xl text-lg leading-8 text-white/60">A synthetic release assurance report showing how Shyena connects journeys, evaluation, security, findings and governance evidence.</p><div className="mt-8 flex flex-wrap gap-3"><a href="/sample-report.pdf" download className="inline-flex h-11 items-center gap-2 rounded-lg bg-[#e87512] px-5 text-sm font-bold text-white">Download PDF <Download className="h-4 w-4"/></a><Link to="/contact" className="inline-flex h-11 items-center gap-2 rounded-lg border border-white/15 px-5 text-sm font-bold text-white">Discuss your system <ArrowRight className="h-4 w-4"/></Link></div></div></div></section>
<section><div className="mx-auto max-w-[1200px] px-5 py-12 sm:px-8 lg:px-10 lg:py-16"><div className="rounded-2xl border border-[#e1e4e9] bg-white p-6 shadow-sm sm:p-8"><div className="flex flex-wrap items-center justify-between gap-4 border-b border-[#e6e8ed] pb-5"><div><div className="font-mono text-[9px] font-bold uppercase tracking-[.16em] text-[#e87512]">Sample report · Synthetic demonstration only</div><h2 className="mt-2 text-2xl font-extrabold">Customer Service Bot v2.8</h2></div><div className="rounded-lg bg-red-50 px-4 py-2 text-sm font-extrabold text-red-700">VERDICT · BLOCK</div></div>
<div className="mt-7 grid gap-3 sm:grid-cols-4">{[["P1 findings","3"],["P2 findings","5"],["P3 findings","12"],["Evidence traces","214"]].map(([a,b])=><div key={a} className="rounded-xl border border-[#e5e7eb] bg-[#fafbfc] p-5"><div className="text-xs text-[#69707d]">{a}</div><div className="mt-2 text-3xl font-extrabold">{b}</div></div>)}</div>
<div className="mt-8 overflow-x-auto rounded-xl border border-[#e5e7eb]"><table className="w-full min-w-[680px] text-left text-sm"><thead className="bg-[#fafbfc] text-xs uppercase tracking-[.1em] text-[#69707d]"><tr><th className="px-5 py-4">Layer</th><th className="px-5 py-4">Result</th><th className="px-5 py-4">Evidence</th></tr></thead><tbody><tr key={a} className="border-t border-[#e8eaee]"><td className="px-5 py-4 font-semibold">Deterministic</td><td className="px-5 py-4 font-bold text-emerald-700">PASS</td><td className="px-5 py-4 text-[#69707d]">Business rules and API assertions</td></tr>,<tr key={a} className="border-t border-[#e8eaee]"><td className="px-5 py-4 font-semibold">Semantic</td><td className="px-5 py-4 font-bold text-amber-700">REVIEW</td><td className="px-5 py-4 text-[#69707d]">Answer-quality evaluation</td></tr>,<tr key={a} className="border-t border-[#e8eaee]"><td className="px-5 py-4 font-semibold">Orchestration</td><td className="px-5 py-4 font-bold text-red-700">FAIL</td><td className="px-5 py-4 text-[#69707d]">Agent/tool trajectory</td></tr>,<tr key={a} className="border-t border-[#e8eaee]"><td className="px-5 py-4 font-semibold">Security</td><td className="px-5 py-4 font-bold text-red-700">FAIL</td><td className="px-5 py-4 text-[#69707d]">Adversarial testing</td></tr>
</tbody></table></div>
<div className="mt-8 grid gap-4 md:grid-cols-3"><article className="rounded-xl border border-[#e5e7eb] bg-[#fafbfc] p-5"><div className="font-mono text-[9px] font-bold uppercase tracking-[.12em] text-[#e87512]">Finding F-001</div><h3 className="mt-2 font-bold">Approval bypass</h3><p className="mt-2 text-sm leading-6 text-[#69707d]">Quotation can progress while approval state is pending.</p></article>,<article className="rounded-xl border border-[#e5e7eb] bg-[#fafbfc] p-5"><div className="font-mono text-[9px] font-bold uppercase tracking-[.12em] text-[#e87512]">Security</div><h3 className="mt-2 font-bold">Art. 50 disclosure</h3><p className="mt-2 text-sm leading-6 text-[#69707d]">AI disclosure missing in the illustrative voice-channel scenario.</p></article>,<article className="rounded-xl border border-[#e5e7eb] bg-[#fafbfc] p-5"><div className="font-mono text-[9px] font-bold uppercase tracking-[.12em] text-[#e87512]">Evidence pack</div><h3 className="mt-2 font-bold">Reproducible</h3><p className="mt-2 text-sm leading-6 text-[#69707d]">Traces, screenshots, API evidence and re-run history are linked.</p></article></div>
<p className="mt-8 border-t border-[#e6e8ed] pt-5 text-xs leading-5 text-[#7a8290]">Synthetic demonstration only. Customer Service Bot v2.8, findings, counts and evidence are illustrative and are not a real customer, production environment or executed client run.</p>
</div></div></section></main>}