import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowLeft, ArrowRight, Check, Download } from "lucide-react";
export const Route=createFileRoute("/sample-report")({head:()=>({links:[{rel:"canonical",href:"https://www.shyena.eu/sample-report"}],meta:[
{title:"Sample Release Assurance Report | Shyena"},
{name:"description",content:"Synthetic sample AI assurance report showing journey evidence, four-layer evaluation, security findings and governance mapping."},
{property:"og:title",content:"Sample Release Assurance Report | Shyena"},
{property:"og:description",content:"Synthetic assurance evidence for a customer service AI agent."},
{property:"og:url",content:"https://www.shyena.eu/sample-report"}
]}),component:SampleReport});
function SampleReport(){return <main className="bg-[#f7f8fa] text-[#17213f]">
<section className="bg-[#07101f] text-white"><div className="mx-auto max-w-[1100px] px-5 py-16 sm:px-8 lg:py-20"><Link to="/" className="inline-flex items-center gap-2 text-sm text-white/60"><ArrowLeft className="h-4 w-4"/>Home</Link><div className="mt-10 font-mono text-[10px] font-bold uppercase tracking-[.2em] text-[#f18a32]">Sample report</div><h1 className="mt-4 font-[Sora] text-5xl font-extrabold tracking-[-.055em] sm:text-6xl">Release assurance evidence.</h1><p className="mt-5 max-w-3xl text-lg leading-8 text-white/60">Synthetic example only. No client, employer or production data is used. Use your browser's Print → Save as PDF to download a PDF copy.</p><div className="mt-7 flex flex-wrap gap-3"><a href="/api/sample-report-pdf" className="inline-flex h-11 items-center gap-2 rounded-lg bg-[#e87512] px-5 text-sm font-bold text-white"><Download className="h-4 w-4"/>Download sample PDF</a><button type="button" onClick={()=>window.print()} className="inline-flex h-11 items-center gap-2 rounded-lg border border-white/15 px-5 text-sm font-bold text-white/80">Print / Save as PDF</button></div></div></section>
<section className="mx-auto max-w-[1100px] px-5 py-12 sm:px-8 lg:py-16">
<div className="rounded-2xl border border-[#dfe3e8] bg-white p-6 shadow-sm sm:p-8">
<div className="flex flex-col justify-between gap-4 border-b border-[#e6e8ed] pb-6 sm:flex-row sm:items-start"><div><div className="text-xs font-bold uppercase tracking-[.14em] text-[#e87512]">Illustrative · Synthetic demo bot</div><h2 className="mt-2 text-2xl font-extrabold">Customer Service Bot v2.8</h2></div><span className="inline-flex h-9 items-center rounded-lg bg-red-50 px-3 text-xs font-bold text-red-700">BLOCK</span></div>
<div className="mt-7 grid gap-3 sm:grid-cols-4">{[["Deterministic","PASS"],["Semantic","REVIEW"],["Orchestration","FAIL"],["Security","FAIL"]].map(([a,b])=><div key={a} className="rounded-xl border border-[#e1e4e9] bg-[#fafbfc] p-4"><div className="text-xs text-[#69707d]">{a}</div><div className="mt-2 font-bold">{b}</div></div>)}</div>
<div className="mt-10"><h3 className="text-xl font-extrabold">Findings</h3><div className="mt-4 space-y-3">{["P1 — Wrong tool selected for a customer request.","P1 — Adversarial prompt reached an unsafe execution branch.","P2 — Answer omitted a required policy explanation."].map(x=><div key={x} className="flex gap-3 rounded-xl border border-[#e1e4e9] p-4 text-sm"><Check className="mt-0.5 h-4 w-4 shrink-0 text-[#e87512]"/>{x}</div>)}</div></div>
<div className="mt-10"><h3 className="text-xl font-extrabold">Governance evidence</h3><div className="mt-4 overflow-x-auto rounded-xl border border-[#e1e4e9]"><table className="w-full min-w-[620px] text-left text-sm"><thead className="bg-[#fafbfc]"><tr><th className="px-4 py-3">Requirement</th><th className="px-4 py-3">Evidence</th><th className="px-4 py-3">Status</th></tr></thead><tbody>{[["AI disclosure","Conversation trace","OPEN"],["Release gate","Evaluation run","PASS"],["Security control","Attack evidence","FAIL"]].map(r=><tr key={r[0]} className="border-t border-[#e8eaee]">{r.map((x,i)=><td key={i} className="px-4 py-3">{x}</td>)}</tr>)}</tbody></table></div></div>
<div className="mt-10 rounded-xl bg-[#17213f] p-5 text-white"><div className="text-xs font-bold uppercase tracking-[.14em] text-[#f18a32]">Evidence chain</div><div className="mt-2 text-sm leading-7 text-white/70">Business journey → agent execution → trace → evaluation → finding → affected component → release decision.</div></div>
</div>
<div className="mt-8 text-center"><Link to="/contact" className="inline-flex h-11 items-center gap-2 rounded-lg bg-[#e87512] px-5 text-sm font-bold text-white">Apply this model to your AI system <ArrowRight className="h-4 w-4"/></Link></div>
</section></main>}
