import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowRight, Check, ShieldCheck } from "lucide-react";

export const Route = createFileRoute("/vera")({ head:()=>({meta:[{title:"Vera | Cognigy Agent Evaluation | Shyena"},{name:"description",content:"Vera runs and evaluates goal-driven tests against Cognigy AI Agents."}]}), component:Vera });

const checks=["Tool calls and arguments","Resulting state","LLM-as-judge with written reasoning","Execution integrity","Prompt injection","Unverified actions","Cross-customer data"];
function Vera(){return <div className="bg-white text-[#17213f]">
<section className="bg-[#07101f] text-white"><div className="mx-auto max-w-[1280px] px-5 py-20 sm:px-8 lg:px-10 lg:py-28"><p className="font-mono text-xs font-bold uppercase tracking-[.2em] text-[#f18a32]">Vera · Execution & evaluation</p><h1 className="mt-5 max-w-5xl font-[Sora] text-[clamp(3rem,6.5vw,6.5rem)] font-extrabold leading-[.9] tracking-[-.065em]">Run the real conversation. Evaluate what actually happened.</h1><p className="mt-7 max-w-3xl text-lg leading-8 text-white/65">Vera runs persona-driven conversations against the agent endpoint and evaluates the journey using deterministic assertions, semantic judgement and an execution-integrity gate.</p></div></section>
<section><div className="mx-auto max-w-[1280px] px-5 py-14 sm:px-8 lg:px-10 lg:py-20"><div className="grid gap-4 md:grid-cols-2">{checks.map((x,i)=><div key={x} className="flex gap-4 rounded-xl border border-[#e2e5ea] bg-white p-6"><span className="font-mono text-xs text-[#9aa1ad]">0{i+1}</span><div><h2 className="font-bold">{x}</h2><p className="mt-2 text-sm leading-6 text-[#667085]">{i===3?"A broken, incomplete or errored run can never pass.":i===2?"Semantic evaluation includes written reasoning so the verdict is inspectable.":"The check is preserved as part of the test evidence."}</p></div></div>)}</div></div></section>
<section className="bg-[#fafbfc]"><div className="mx-auto max-w-[1000px] px-5 py-16 text-center sm:px-8 lg:py-20"><ShieldCheck className="mx-auto h-8 w-8 text-[#f18a32]"/><h2 className="mt-5 text-3xl font-extrabold">Boundary behaviour is tested, not assumed.</h2><p className="mx-auto mt-4 max-w-2xl text-base leading-7 text-[#596273]">Prompt injection, unverified actions and cross-customer data boundaries can be represented as test cases alongside normal business journeys.</p><Link to="/sample-report" className="mt-8 inline-flex h-11 items-center gap-2 rounded-lg bg-[#17213f] px-5 text-sm font-bold text-white">View sample report <ArrowRight className="h-4 w-4"/></Link></div></section>
</div>}
