import type { SeoLandingConfig } from "./seo-landing";

const commonRelated = [{ label: "Vera — AI agent testing", href: "/vera" }, { label: "Nexus — Cognigy agent intelligence", href: "/nexus" }, { label: "Chakra — AI security assurance", href: "/chakra" }, { label: "Autonomous testing", href: "/autonomous-testing" }, { label: "Evaluation model", href: "/docs/evaluation-model" }];

export const seoPages: Record<string, SeoLandingConfig> = {
  "/ai-agent-testing": { path: "/ai-agent-testing", eyebrow: "AI agent assurance", title: "AI Agent Testing Platform", description: "Test AI agents through realistic journeys, evaluate behaviour, verify execution integrity and produce evidence-backed release decisions with Shyena.", intro: "AI agent testing must validate more than the final answer. Shyena tests goals, multi-turn behaviour, business rules, tool use, execution integrity and security so teams can understand what actually happened during a run.", sections: [
    { heading: "Test complete agent journeys", body: "Define a business goal, persona and behavioural playbook. Let the test adapt to the agent's live responses instead of replaying one brittle transcript.", bullets: ["Goal-driven scenarios", "Multi-turn conversations", "Edge and recovery paths"] },
    { heading: "Evaluate behaviour, not only answers", body: "Combine deterministic assertions with semantic evaluation so quality, business rules and system behaviour are judged together.", bullets: ["Deterministic business rules", "LLM-as-a-judge semantic evaluation", "Turn- and run-level evidence"] },
    { heading: "Protect against false passes", body: "Execution integrity checks whether the journey actually completed as intended. A convincing response cannot hide a missing tool call, premature termination or failed business state.", bullets: ["Expected route verification", "Tool-call and state checks", "Terminal-state validation"] },
    { heading: "Connect testing to release", body: "Keep the journey, conversation, evaluation, findings, component and verdict connected so a release decision can be reconstructed from evidence.", bullets: ["CI/CD release gates", "Traceable evidence", "Governed GO / NO-GO / REVIEW decisions"] },
  ], related: commonRelated, faqs: [
    { q: "What is AI agent testing?", a: "AI agent testing validates whether an agent achieves its intended goal while respecting business rules, tool-use constraints, state transitions, security controls and quality expectations across realistic interactions." },
    { q: "How is AI agent testing different from chatbot testing?", a: "Agent testing examines the full execution path, including orchestration, tools, state and side effects, rather than evaluating only the generated conversation text." },
    { q: "Can AI agent tests run in CI/CD?", a: "Yes. Shyena is designed to connect assurance runs and release evidence to engineering workflows and release gates." },
  ] },
  "/ai-agent-evaluation": { path: "/ai-agent-evaluation", eyebrow: "Evaluation engineering", title: "AI Agent Evaluation Framework", description: "Evaluate AI agents with deterministic checks, semantic judgment, trajectory integrity, security controls and evidence-backed release gates.", intro: "A single quality score cannot establish that an AI agent behaved correctly. Shyena separates observable facts, semantic behaviour, execution integrity and security into explicit evaluation layers.", sections: [
    { heading: "Deterministic evaluation", body: "Validate exact facts that should never be delegated to probabilistic judgment: business rules, authorization, required states, tool calls and invariants.", bullets: ["Exact assertions", "Expected state validation", "Policy and business-rule gates"] },
    { heading: "Semantic evaluation", body: "Use LLM-based judgment where interpretation is required, while preserving the input evidence, criterion, score, threshold and reasoning used by the evaluator.", bullets: ["Answer relevance", "Business usefulness", "Conversation quality"] },
    { heading: "Trajectory integrity", body: "Evaluate whether the system took an acceptable path to the intended outcome, including tool use, routing, handoffs, loops and termination.", bullets: ["Expected route", "Unexpected tool invocation detection", "No premature termination"] },
    { heading: "Security as a gate", body: "Security findings become part of the release evidence chain rather than a detached security report.", bullets: ["Trust-boundary testing", "Adversarial campaigns", "Verified release controls"] },
  ], related: commonRelated, faqs: [
    { q: "What should an AI agent evaluation measure?", a: "It should measure the dimensions relevant to the system: deterministic business correctness, semantic quality, execution integrity, security and the evidence required to support the release decision." },
    { q: "Is LLM-as-a-judge enough for AI evaluation?", a: "No. Semantic judgment is useful for interpretation, but deterministic facts, execution integrity and security boundaries require explicit controls." },
    { q: "Can evaluation results become release gates?", a: "Yes. Evaluation signals can be combined into governed release gates with evidence attached to each decision." },
  ] },
  "/ai-agent-testing-platform": { path: "/ai-agent-testing-platform", eyebrow: "Enterprise AI quality engineering", title: "AI Agent Testing & Evaluation Platform", description: "Enterprise AI agent testing, evaluation and security assurance in one evidence chain — from realistic journeys to governed release decisions.", intro: "Shyena connects system understanding, AI agent testing, evaluation, security and release evidence. The platform is designed for teams that need to explain and defend an AI release, not just report a score.", sections: [
    { heading: "Understand with Nexus", body: "Map agent logic, orchestration, dependencies and business journeys before generating test intent. Nexus is live today with Cognigy source adapters.", bullets: ["Structural agent model", "Decision and path analysis", "Test-spec provenance"] },
    { heading: "Test and evaluate with Vera", body: "Run realistic multi-turn journeys and combine semantic, deterministic and execution-integrity evidence into a release verdict.", bullets: ["Goal-driven scenarios", "LLM-as-a-judge", "Cognigy conversational and voice agents"] },
    { heading: "Defend with Chakra", body: "Probe agent capabilities, trust boundaries and adversarial paths, verify impact and carry security findings into release controls.", bullets: ["Attack-chain verification", "Business-policy testing", "Evidence and regression controls"] },
    { heading: "Release with evidence", body: "Connect scope, gates, runs, traces, findings, exceptions and the final verdict so engineering and governance teams can audit the decision.", bullets: ["Release evidence", "CI/CD integration", "Governed decisions"] },
  ], related: commonRelated, faqs: [
    { q: "What does an AI agent testing platform do?", a: "It provides the infrastructure to define, execute and evaluate realistic agent journeys, inspect behaviour and evidence, and connect results to engineering and release workflows." },
    { q: "Does Shyena replace existing test automation?", a: "Shyena is designed to work with existing engineering environments and execution engines such as Playwright rather than requiring teams to discard their established tooling." },
    { q: "Which agent platforms does Shyena support?", a: "Cognigy is the live source adapter for Nexus today. Other agent frameworks and knowledge-base integrations are described as roadmap items where applicable." },
  ] },
  "/conversational-ai-testing": { path: "/conversational-ai-testing", eyebrow: "Conversational AI QA", title: "Conversational AI Testing", description: "Test conversational AI across realistic multi-turn journeys, semantic quality, business rules, execution integrity and release evidence.", intro: "Conversational AI can take multiple valid paths to the same customer goal. Testing therefore needs to evaluate outcomes and constraints while allowing runtime variation in wording and route.", sections: [
    { heading: "Goal-driven conversation tests", body: "Describe what the customer is trying to achieve instead of hard-coding every turn. The simulated user can adapt to the live agent response.", bullets: ["Customer goals", "Personas and playbooks", "Recovery paths"] },
    { heading: "Multi-turn evaluation", body: "Evaluate the complete interaction, not isolated messages. Preserve conversation context and the evidence behind each important judgment.", bullets: ["Turn-level evaluation", "Conversation-level evaluation", "Evidence-linked findings"] },
    { heading: "Business-rule validation", body: "Use deterministic assertions for requirements that must be exact, including required handoffs, authorization and business state changes.", bullets: ["Business invariants", "Required state", "Correct handoff"] },
    { heading: "Voice and conversational agents", body: "Apply the same assurance model to conversational and voice workflows where the system has to achieve a goal through an adaptive interaction.", bullets: ["Voice agent journeys", "Agent orchestration", "Release regression"] },
  ], related: [{ label: "Vera", href: "/vera" }, { label: "Cognigy testing", href: "/cognigy-testing" }, { label: "AI agent testing", href: "/ai-agent-testing" }, { label: "Evaluation model", href: "/docs/evaluation-model" }], faqs: [
    { q: "How do you test a conversational AI agent?", a: "Define a business goal and persona, execute a realistic multi-turn journey, evaluate semantic and deterministic behaviour, verify execution integrity and retain the evidence behind the verdict." },
    { q: "Can conversational AI tests allow different valid responses?", a: "Yes. Goal-driven testing can allow valid wording and path variation while enforcing deterministic business constraints and the intended outcome." },
    { q: "Can Shyena test Cognigy conversational agents?", a: "Yes. Vera can exercise Cognigy conversational and voice agents through realistic customer-style journeys." },
  ] },
  "/autonomous-ai-testing": { path: "/autonomous-ai-testing", eyebrow: "Autonomous quality engineering", title: "Autonomous AI Testing", description: "Give Shyena a testing goal and let agents explore, discover coverage gaps, engineer Playwright automation, execute, diagnose and produce release evidence.", intro: "Autonomous testing goes beyond generating test code. The system must understand the application, discover meaningful journeys, challenge coverage, execute tests, investigate failures and prove the result.", sections: [
    { heading: "Explore before generating", body: "Understand the application, repository, APIs, dependencies and existing automation before deciding what needs to be tested.", bullets: ["Application exploration", "Repository understanding", "Existing-suite analysis"] },
    { heading: "Discover risk and coverage gaps", body: "Find critical user journeys, business rules, failure conditions and paths that existing regression automation does not cover.", bullets: ["Journey discovery", "Coverage intelligence", "Risk-focused scenarios"] },
    { heading: "Engineer executable automation", body: "Generate repository-native Playwright tests, fixtures and supporting automation from the testing intent rather than producing disconnected scripts.", bullets: ["Playwright automation", "Fixtures and data", "Independent scenario challenge"] },
    { heading: "Diagnose, heal and prove", body: "Correlate browser evidence, APIs, logs and execution history, apply governed remediation and reconnect the final result to release evidence.", bullets: ["Failure classification", "Safe automation remediation", "Evidence-backed release confidence"] },
  ], related: [{ label: "AI agent testing", href: "/ai-agent-testing" }, { label: "Playwright automation", href: "/autonomous-testing" }, { label: "Vera", href: "/vera" }, { label: "Documentation", href: "/docs" }], faqs: [
    { q: "What is autonomous AI testing?", a: "Autonomous AI testing uses agents to perform substantial parts of the testing workflow: understanding the target, discovering scenarios, engineering automation, executing, investigating failures and producing evidence." },
    { q: "How is autonomous testing different from AI test generation?", a: "AI test generation primarily creates scripts from an input. Autonomous testing extends the loop into exploration, coverage discovery, execution, diagnosis and proof." },
    { q: "Does Shyena use Playwright?", a: "Yes. Shyena's autonomous testing capability can engineer repository-native Playwright automation while keeping the team's existing engineering environment in place." },
  ] },
  "/llm-evaluation": { path: "/llm-evaluation", eyebrow: "LLM and agent evaluation", title: "LLM Evaluation for AI Agents", description: "Evaluate generated answers with semantic criteria while keeping deterministic facts, execution integrity and security under explicit controls.", intro: "LLM evaluation is one layer of AI assurance. It is useful when a result requires interpretation, but it should not be treated as a universal truth signal or as a substitute for deterministic system validation.", sections: [
    { heading: "Semantic quality", body: "Evaluate relevance, correctness, usefulness, completeness and other criteria that require interpretation of language and context.", bullets: ["Answer relevance", "Helpfulness and completeness", "Conversation quality"] },
    { heading: "LLM-as-a-judge controls", body: "Preserve the evaluation criterion, score, threshold, reason and input evidence so semantic judgments remain inspectable.", bullets: ["Explicit criteria", "Thresholds", "Judge configuration"] },
    { heading: "Separate retrieval from generation", body: "For RAG systems, evaluate retrieval quality separately from generator quality so a strong answer cannot hide poor retrieval or unsupported context.", bullets: ["Context relevance", "Recall and precision", "Faithfulness and answer relevance"] },
    { heading: "Connect scores to execution", body: "Semantic evaluation becomes more useful when connected to the actual conversation, trace, deterministic assertions and release gate.", bullets: ["Evidence chain", "Execution integrity", "Release disposition"] },
  ], related: [{ label: "Vera", href: "/vera" }, { label: "Evaluation model", href: "/docs/evaluation-model" }, { label: "AI agent testing", href: "/ai-agent-testing" }, { label: "RAG assurance", href: "/docs/evaluation-model" }], faqs: [
    { q: "What is LLM evaluation?", a: "LLM evaluation measures generated outputs against defined quality criteria such as relevance, correctness, completeness, faithfulness or usefulness." },
    { q: "What is LLM-as-a-judge?", a: "LLM-as-a-judge uses another model to assess an output against explicit criteria. It is a semantic evaluation mechanism, not a replacement for deterministic assertions or security controls." },
    { q: "Can LLM evaluation be used in release gates?", a: "Yes, provided the criteria, thresholds, evidence and failure semantics are explicit and combined with the other assurance layers required by the system." },
  ] },
  "/ai-regression-testing": { path: "/ai-regression-testing", eyebrow: "AI regression assurance", title: "AI Regression Testing", description: "Run repeatable AI agent regression tests across releases and detect behavioural, business-rule, execution and security regressions before production.", intro: "AI systems can regress without a traditional UI or API contract changing. Regression assurance must protect customer journeys, business invariants, agent trajectories, generated answers and security controls.", sections: [
    { heading: "Regression around business goals", body: "Maintain tests around important customer outcomes and constraints rather than only exact wording or fixed conversation transcripts.", bullets: ["Critical journeys", "Business invariants", "Edge and recovery paths"] },
    { heading: "Detect behavioural drift", body: "Compare semantic and deterministic outcomes while preserving the evidence needed to understand what changed.", bullets: ["Quality thresholds", "Expected behaviour", "Traceable differences"] },
    { heading: "Protect execution integrity", body: "Catch changes that cause wrong routing, missing tool calls, unauthorized mutations, loops or premature termination even when the final response appears acceptable.", bullets: ["Trajectory checks", "Tool-call controls", "Terminal-state checks"] },
    { heading: "Gate releases", body: "Use regression outcomes as governed release evidence and connect failures to the affected component and release candidate.", bullets: ["CI/CD integration", "Release gates", "Audit-ready evidence"] },
  ], related: [{ label: "AI agent testing", href: "/ai-agent-testing" }, { label: "Vera", href: "/vera" }, { label: "Release evidence", href: "/docs/reporting" }, { label: "Autonomous testing", href: "/autonomous-testing" }], faqs: [
    { q: "What is AI regression testing?", a: "AI regression testing repeatedly checks critical agent behaviours and outcomes after changes to models, prompts, orchestration, tools, retrieval, applications or configuration." },
    { q: "Can regression tests use flexible conversations?", a: "Yes. Goal-driven scenarios can allow valid conversational variation while keeping deterministic business requirements and execution constraints explicit." },
    { q: "Can AI regression tests block a release?", a: "Yes. Regression gates can be connected to release decisions when the required evidence and failure policy are defined." },
  ] },
  "/ai-agent-security-testing": { path: "/ai-agent-security-testing", eyebrow: "AI security assurance", title: "AI Agent Security Testing", description: "Discover agent capabilities, model trust boundaries, run controlled adversarial testing, verify impact and carry security evidence into release decisions.", intro: "Agent security depends on the path from untrusted input through retrieval and model decisions into tools, permissions and side effects. Security testing should verify that complete chain.", sections: [
    { heading: "Discover the security surface", body: "Map agents, tools, memory, permissions and trust boundaries before selecting attacks.", bullets: ["Capabilities and tools", "Permissions", "Trust boundaries"] },
    { heading: "Attack realistic paths", body: "Run controlled adversarial campaigns against high-risk paths and adapt execution based on observed system behaviour.", bullets: ["Prompt injection", "Tool-chain abuse", "Adversarial journeys"] },
    { heading: "Verify impact", body: "Do not stop at a vulnerability flag. Trace the attack from input through model decision and tool invocation to observed impact.", bullets: ["Attack-chain evidence", "Side-effect verification", "Business-policy validation"] },
    { heading: "Make security a release gate", body: "Verified security findings become structured assertions and regression controls inside the same evidence chain as functional assurance.", bullets: ["Severity and control mapping", "Release blocking rules", "Replayable evidence"] },
  ], related: [{ label: "Chakra", href: "/chakra" }, { label: "Cognigy security testing", href: "/blog/cognigy-agent-security-testing-with-ziran" }, { label: "AI agent testing", href: "/ai-agent-testing" }, { label: "Evaluation model", href: "/docs/evaluation-model" }], faqs: [
    { q: "What is AI agent security testing?", a: "It tests whether an agent can be manipulated into unsafe behaviour, unauthorized tool use, policy violations or harmful side effects through adversarial inputs and system paths." },
    { q: "How is agent security different from prompt testing?", a: "Agent security includes the complete system path: model behaviour, tools, memory, permissions, orchestration and observable side effects, not only prompt and response text." },
    { q: "Can security findings block AI releases?", a: "Yes. Verified security findings can be mapped to explicit release gates and regression controls." },
  ] },
  "/cognigy-testing": { path: "/cognigy-testing", eyebrow: "Cognigy assurance", title: "Cognigy Agent Testing", description: "Test Cognigy conversational and voice agents with goal-driven journeys, deterministic assertions, semantic evaluation, execution-integrity checks and release evidence.", intro: "Cognigy agents can contain flows, branches, business rules, integrations and handoffs that are difficult to cover with manually authored transcripts. Shyena uses the agent's actual logic to improve test intent and coverage.", sections: [
    { heading: "Map the Cognigy agent", body: "Nexus reads live Cognigy flow definitions and builds a structural model of journeys, decisions, modules, integrations and target outcomes.", bullets: ["Live flow definitions", "Branch and path analysis", "Dependency impact"] },
    { heading: "Generate test specifications", body: "Draft test specifications against real coverage obligations and apply structural and semantic review before a spec is ready to run.", bullets: ["Coverage obligations", "Semantic review", "Provenance and revision lineage"] },
    { heading: "Execute realistic journeys", body: "Vera exercises Cognigy conversational and voice agents through customer-style journeys and evaluates the resulting execution.", bullets: ["Multi-turn journeys", "Voice and conversational workflows", "Deterministic + semantic evaluation"] },
    { heading: "Secure and release", body: "Chakra can extend the assurance chain into security boundaries, while reporting connects findings and evidence to the release decision.", bullets: ["Security assurance", "Release evidence", "Regression controls"] },
  ], related: [{ label: "Nexus", href: "/nexus" }, { label: "Vera", href: "/vera" }, { label: "Chakra", href: "/chakra" }, { label: "How to test a Cognigy agent", href: "/blog/how-to-test-a-cognigy-agent" }], faqs: [
    { q: "How do you test a Cognigy agent?", a: "Map the real Cognigy flows, identify critical paths and business rules, generate or author goal-driven test intent, execute against the agent, evaluate behaviour and preserve the evidence behind the verdict." },
    { q: "Can Shyena generate Cognigy test specifications?", a: "Nexus reads live Cognigy flow definitions, builds a structural model and drafts test specifications against coverage obligations, with validation and provenance." },
    { q: "Can Shyena test Cognigy voice agents?", a: "Yes. Vera is designed to exercise Cognigy conversational and voice agents through realistic customer-style journeys." },
  ] },
  "/ai-testing-framework": { path: "/ai-testing-framework", eyebrow: "AI quality engineering", title: "AI Agent Testing Framework", description: "A practical framework for AI agent testing that separates deterministic validation, semantic evaluation, trajectory integrity, security and release evidence.", intro: "A useful AI testing framework needs to define what must be true, how the system will be observed, which judgments are deterministic or semantic, how execution integrity is proven and how failures affect release decisions.", sections: [
    { heading: "Define test intent", body: "Start from a business goal, persona, behavioural playbook, invariants and evidence requirements instead of a brittle transcript.", bullets: ["Goals and personas", "Behavioural playbooks", "Business invariants"] },
    { heading: "Separate evaluation layers", body: "Keep exact facts, semantic judgments, trajectory integrity and security controls explicit so a strong score cannot hide a critical failure.", bullets: ["Deterministic", "Semantic", "Trajectory and security"] },
    { heading: "Build an evidence graph", body: "Link the test specification, agent build, environment, conversation, trace, assertions, evaluations and security findings to the final verdict.", bullets: ["Traceability", "Reproducibility", "Audit-ready evidence"] },
    { heading: "Operationalize release gates", body: "Turn the framework into repeatable engineering workflows with CI/CD integration, exceptions and governed release policy.", bullets: ["Release candidate scope", "Gate semantics", "GO / NO-GO / REVIEW"] },
  ], related: [{ label: "Evaluation model", href: "/docs/evaluation-model" }, { label: "AI agent testing", href: "/ai-agent-testing" }, { label: "Release evidence", href: "/docs/reporting" }, { label: "Documentation", href: "/docs" }], faqs: [
    { q: "What should an AI agent testing framework contain?", a: "At minimum: test intent, deterministic assertions, semantic evaluation where appropriate, execution-integrity checks, security controls, evidence traceability and release-gate semantics." },
    { q: "Why separate deterministic and semantic testing?", a: "Exact business and system facts should be verified deterministically. Semantic evaluation is appropriate where interpretation is required. Keeping them separate makes failures more auditable." },
    { q: "Can the framework work with existing QA tools?", a: "Yes. The framework can sit alongside existing test automation, CI/CD, APIs, observability and execution engines." },
  ] },
  "/ai-release-assurance": { path: "/ai-release-assurance", eyebrow: "Release governance", title: "AI Release Assurance", description: "Turn AI testing, evaluation and security results into traceable release evidence and governed GO, NO-GO or REVIEW decisions.", intro: "A dashboard is a navigation layer. Release assurance needs a defensible evidence chain that explains what was tested, what failed, what risk remains and why the release decision follows.", sections: [
    { heading: "Define release scope", body: "Identify the release candidate, agent/application version, test specification, environment and assurance scope before evaluating results.", bullets: ["Release ID", "Agent build", "Environment identity"] },
    { heading: "Apply explicit gates", body: "Combine deterministic, semantic, execution-integrity and security gates with clear pass/fail semantics and documented exceptions.", bullets: ["Gate results", "Exceptions", "Policy thresholds"] },
    { heading: "Keep evidence traceable", body: "Allow reviewers to drill from a release statement to the gate, evaluation, conversation, trace and raw observation behind it.", bullets: ["Evidence hierarchy", "Run IDs", "Evaluator configuration"] },
    { heading: "Make the decision auditable", body: "Produce a governed verdict with the evidence and rationale needed by engineering, quality, security and governance stakeholders.", bullets: ["GO / NO-GO / REVIEW", "Audit trail", "Release workflow integration"] },
  ], related: [{ label: "Reporting & release evidence", href: "/docs/reporting" }, { label: "AI agent testing", href: "/ai-agent-testing" }, { label: "AI security testing", href: "/ai-agent-security-testing" }, { label: "Pricing", href: "/pricing" }], faqs: [
    { q: "What is AI release assurance?", a: "AI release assurance is the controlled process of establishing evidence that an AI system meets required quality, behavioural, execution, security and governance conditions before release." },
    { q: "What should AI release evidence contain?", a: "It should identify the release, system version, test specification, environment, run IDs, evaluator version, gate results, exceptions, underlying evidence and final verdict." },
    { q: "Can AI release assurance integrate with CI/CD?", a: "Yes. Release evidence and gates can be incorporated into engineering delivery workflows so assurance is part of the release process." },
  ] },
  "/ai-production-readiness": { path: "/ai-production-readiness", eyebrow: "Production readiness", title: "AI Production Readiness Assessment", description: "Assess whether an AI agent is ready for production across behaviour, business rules, execution integrity, security and release evidence.", intro: "Production readiness is not established by a model benchmark or a single evaluation score. It requires evidence that the complete system behaves correctly under realistic journeys and that critical risks are controlled.", sections: [
    { heading: "Validate critical journeys", body: "Exercise the customer and operational journeys that matter most to the business, including edge and recovery paths.", bullets: ["Critical business journeys", "Failure and recovery paths", "Realistic multi-turn execution"] },
    { heading: "Verify behaviour and state", body: "Check answers, business rules, tool calls, authorization, state transitions and terminal outcomes using the right evaluation method for each claim.", bullets: ["Deterministic assertions", "Semantic evaluation", "Execution integrity"] },
    { heading: "Challenge security boundaries", body: "Test high-risk trust boundaries and verify whether adversarial inputs can cause unsafe tool use, policy violations or harmful side effects.", bullets: ["Adversarial testing", "Tool and permission controls", "Verified impact"] },
    { heading: "Produce a readiness decision", body: "Connect findings and evidence into a governed release assessment that can be reviewed and repeated after changes.", bullets: ["Readiness evidence", "Release gates", "Regression controls"] },
  ], related: [{ label: "AI agent testing", href: "/ai-agent-testing" }, { label: "AI security testing", href: "/ai-agent-security-testing" }, { label: "AI release assurance", href: "/ai-release-assurance" }, { label: "Contact Shyena", href: "/contact" }], faqs: [
    { q: "What does AI production readiness mean?", a: "It means the AI system has evidence supporting required behaviour, business correctness, execution integrity, security and operational controls for its intended production scope." },
    { q: "Is a high LLM evaluation score enough for production?", a: "No. A high semantic score does not prove business correctness, execution integrity, authorization, security or successful completion of the intended goal." },
    { q: "Can production readiness be reassessed after changes?", a: "Yes. The assessment can become a repeatable regression and release-assurance workflow tied to new builds and release candidates." },
  ] },
};
