import { Link } from "@tanstack/react-router";
import { ArrowRight, Check, ShieldCheck } from "lucide-react";

const capabilities = [
  { plain:"Map your agent", product:"Nexus", body:"Understand flows, orchestration, dependencies, tools and critical business journeys before you test.", to:"/nexus", items:["Flow and dependency mapping","Critical journey discovery","Test intent from system structure","Traceability from requirement to journey"] },
  { plain:"Judge every answer", product:"Vera", body:"Run realistic multi-turn journeys and evaluate outcomes across deterministic, semantic and orchestration signals.", to:"/vera", items:["Realistic journey execution","Deterministic assertions","Semantic evaluation","Execution-integrity checks"] },
  { plain:"Attack it safely", product:"Chakra", body:"Probe prompt injection, unsafe tool use, policy boundaries and adversarial execution paths.", to:"/chakra", items:["Adversarial journeys","Prompt-injection probes","Tool and permission checks","Security evidence"] },
  { plain:"Prove it to auditors", product:"Govern", body:"Map findings and traces to governance requirements and preserve evidence across re-runs.", to:"/govern", items:["Requirement-to-evidence mapping","EU AI Act evidence","ISO/IEC 42001 mapping","Evidence packs and re-run history"] }
];

const metrics = [
  ["Task completion","Whether the intended business goal was achieved","Semantic + Orchestration"],
  ["Groundedness","Whether answers are supported by the available knowledge","Semantic"],
  ["Tool correctness","Whether the right tool was selected and used correctly","Orchestration"],
  ["Execution integrity","Whether the journey completed without hidden failures","Deterministic + Orchestration"],
  ["Security control","Whether adversarial paths were contained","Security"],
  ["Business-rule compliance","Whether hard business constraints were satisfied","Deterministic"]
];

export function QualityIntelligencePage() {
  return <main className="bg-white text-[#17213f]">
    <section className="bg-[#07101f] text-white"><div className="mx-auto max-w-[1280px] px-5 py-20 sm:px-8 lg:px-10 lg:py-28"><div className="max-w-5xl"><div className="font-mono text-[10px] font-bold uppercase tracking-[.22em] text-[#f18a32]">AI ASSURANCE ENGINEER</div><h1 className="mt-5 font-[Sora] text-[clamp(3rem,6vw,6rem)] font-extrabold leading-[.9] tracking-[-.065em]">One platform:<br/><span className="text-[#f18a32]">map, judge, attack, prove.</span></h1><p className="mt-7 max-w-3xl text-lg leading-8 text-white/60">Shyena connects system understanding, realistic journey testing, four-layer evaluation, security testing and governance evidence into one assurance chain.</p><div className="mt-8 flex flex-wrap gap-3"><Link to="/contact" className="inline-flex h-11 items-center gap-2 rounded-lg bg-[#e87512] px-5 text-sm font-bold text-white">Book a 30-min call <ArrowRight className="h-4 w-4"/></Link><Link to="/sample-report" className="inline-flex h-11 items-center gap-2 rounded-lg border border-white/15 px-5 text-sm font-bold text-white/80">See sample evidence <ArrowRight className="h-4 w-4"/></Link></div></div></div></section>

    <section className="border-b border-[#e6e8ed]"><div className="mx-auto max-w-[1280px] px-5 py-16 sm:px-8 lg:px-10 lg:py-20"><div className="grid gap-4 md:grid-cols-2">{capabilities.map((cap,i)=><article key={cap.product} className="rounded-2xl border border-[#e1e4e9] bg-[#fafbfc] p-7 sm:p-8"><div className="flex items-center justify-between"><span className="font-mono text-[10px] font-bold tracking-[.16em] text-[#e87512]">0{i+1}</span><span className="rounded-full border border-[#dfe3e8] bg-white px-3 py-1 text-[10px] font-bold">{cap.product}</span></div><h2 className="mt-6 font-[Sora] text-2xl font-extrabold tracking-[-.03em]">{cap.plain} <span className="text-[#8b929d]">({cap.product})</span></h2><p className="mt-3 text-sm leading-6 text-[#69707d]">{cap.body}</p><ul className="mt-5 space-y-2 border-t border-[#e5e7eb] pt-5">{cap.items.map(x=><li key={x} className="flex gap-2 text-sm text-[#596273]"><Check className="mt-0.5 h-4 w-4 shrink-0 text-[#e87512]"/>{x}</li>)}</ul><Link to={cap.to} className="mt-6 inline-flex items-center gap-2 text-sm font-bold">Explore {cap.product} <ArrowRight className="h-4 w-4"/></Link></article>)}</div></div></section>

    <section className="bg-[#f8fafc]"><div className="mx-auto max-w-[1280px] px-5 py-20 sm:px-8 lg:px-10 lg:py-24"><div className="max-w-3xl"><div className="text-sm font-bold text-[#e87512]">Evidence chain</div><h2 className="mt-3 font-[Sora] text-4xl font-extrabold tracking-[-.045em] sm:text-5xl">From journey to defensible release.</h2><p className="mt-5 text-lg leading-8 text-[#69707d]">Shyena keeps the evidence path visible: user goal → agent execution → evaluation → finding → affected component → release decision.</p></div><div className="mt-10 rounded-2xl border border-[#e1e4e9] bg-white p-6 sm:p-8"><div className="mb-3 text-[9px] font-bold uppercase tracking-[.15em] text-[#8b929d]">Illustrative</div><div className="flex flex-wrap items-center justify-center gap-2 text-sm font-bold">{["User goal","Agent","Model / RAG","Tool","API / state","Evaluation","Finding","Verdict"].map((x,i)=><span key={x} className="flex items-center gap-2"><span className="rounded-lg border border-[#dfe3e8] bg-[#fafbfc] px-3 py-2">{x}</span>{i<7 && <ArrowRight className="h-4 w-4 text-[#a4abb6]"/>}</span>)}</div></div></div></section>

    <section className="bg-white"><div className="mx-auto max-w-[1280px] px-5 py-20 sm:px-8 lg:px-10 lg:py-24"><div className="max-w-3xl"><div className="text-sm font-bold text-[#e87512]">Metrics library</div><h2 className="mt-3 font-[Sora] text-4xl font-extrabold tracking-[-.045em] sm:text-5xl">Measure the dimension that failed.</h2></div><div className="mt-9 overflow-x-auto rounded-2xl border border-[#e1e4e9]"><table className="w-full min-w-[680px] text-left text-sm"><thead className="bg-[#fafbfc] text-xs uppercase tracking-[.12em] text-[#69707d]"><tr><th className="px-5 py-4">Metric</th><th className="px-5 py-4">What it measures</th><th className="px-5 py-4">Layer</th></tr></thead><tbody>{metrics.map(([a,b,c])=><tr key={a} className="border-t border-[#e8eaee]"><td className="px-5 py-4 font-bold">{a}</td><td className="px-5 py-4 text-[#69707d]">{b}</td><td className="px-5 py-4 text-[#69707d]">{c}</td></tr>)}</tbody></table></div></div></section>

    <section className="border-y border-[#e6e8ed] bg-[#fafbfc]"><div className="mx-auto max-w-[1280px] px-5 py-20 sm:px-8 lg:px-10 lg:py-24"><div className="grid gap-8 md:grid-cols-2"><div><ShieldCheck className="h-6 w-6 text-[#e87512]"/><h2 className="mt-5 font-[Sora] text-3xl font-extrabold tracking-[-.04em]">Hard gates stay hard.</h2><p className="mt-4 text-base leading-7 text-[#69707d]">Deterministic and security failures are preserved as explicit gates. A strong semantic score cannot average away a failed business rule or unsafe execution path.</p></div><div><h2 className="font-[Sora] text-3xl font-extrabold tracking-[-.04em]">Evidence stays traceable.</h2><p className="mt-4 text-base leading-7 text-[#69707d]">Each finding can be connected to the journey, trace, component, requirement and release decision that produced it.</p></div></div></div></section>

    <section className="bg-[#17213f] text-white"><div className="mx-auto max-w-[1000px] px-5 py-16 text-center sm:px-8 lg:py-20"><h2 className="font-[Sora] text-3xl font-extrabold tracking-[-.04em] sm:text-4xl">Start with one AI system and one evidence question.</h2><Link to="/contact" className="mt-8 inline-flex h-11 items-center gap-2 rounded-lg bg-[#e87512] px-5 text-sm font-bold">Book a 30-min call <ArrowRight className="h-4 w-4"/></Link></div></section>
  </main>;
}
