// AUTO-GENERATED by scripts/generate-content.mjs. Do not edit manually.

export type GeneratedContentMeta = {
  type: "blog" | "docs";
  sourcePath: string;
  title: string;
  slug: string;
  description: string;
  category?: string;
  primary_keyword?: string;
  search_intent?: string;
  author?: string;
  published?: string;
};

export const generatedContent = {
  articles: [
    {
      type: "blog",
      sourcePath: "content/blog/ai-agent-testing-is-a-systems-problem.md",
      title: "AI Agent Testing Is a Systems Problem, Not Just an LLM Evaluation Problem",
      description:
        "Why reliable AI agent assurance has to test goals, orchestration, deterministic contracts, generated answers, and security as one system.",
      slug: "ai-agent-testing-is-a-systems-problem",
      category: "AI Agent Assurance",
      primary_keyword: "AI agent testing",
      search_intent: "informational",
      author: "Shyena Engineering",
      published: "true",
    },
  ],
  docs: [
    {
      type: "docs",
      sourcePath: "content/docs/sage-content-engineering.md",
      title: "SAGE Content Engineering",
      description:
        "How Shyena researches, writes, reviews, verifies, optimizes, and publishes technical content through a multi-agent assurance pipeline.",
      slug: "sage-content-engineering",
      category: "Content Engineering",
      primary_keyword: "AI content engineering",
      search_intent: "informational",
      author: "Shyena Engineering",
      published: "true",
    },
  ],
} as const;
