// AUTO-GENERATED by scripts/generate-public-content.mjs. Do not edit manually.

export type GeneratedContentMeta = {
  type: "blog" | "docs";
  sourcePath: string;
  title: string;
  slug: string;
  description: string;
  category?: string;
  diagram?: string;
  thesis?: string;
  primary_keyword?: string;
  search_intent?: string;
  author?: string;
  published?: string;
};

export const generatedContent = {
  articles: [
    {
      type: "blog",
      sourcePath: "content/blog/ai-agent-testing-is-a-systems-problem.md",
      title: "AI Agent Testing: Why Response Quality Is Not Enough for Production Assurance",
      description: "An AI agent can produce a good answer and still fail the customer's journey. Learn how to test outcomes, orchestration, tools, deterministic contracts, security, and evidence as one assurance system.",
      slug: "ai-agent-testing-is-a-systems-problem",
      category: "AI Agent Assurance",
      diagram: "systems",
      thesis: "A good AI response is not proof that an agent worked. Production assurance must connect business outcome, agent execution, orchestration, deterministic contracts, generated-answer quality, security, and execution evidence into one release decision.",
      primary_keyword: "AI agent testing",
      search_intent: "informational",
      author: "Shyena Engineering",
      published: "true",
    },
  ],
  docs: [
    {
      type: "docs",
      sourcePath: "content/docs/ai-assurance-tokenomics.md",
      title: "AI Assurance Tokenomics",
      description: "Connecting tokens, agent behaviour, assurance effort, value and business impact.",
      slug: "ai-assurance-tokenomics",
      category: "AI Assurance Economics",
      primary_keyword: "AI assurance tokenomics",
      search_intent: "informational",
      author: "Shyena Engineering",
      published: "true",
    },
    {
      type: "docs",
      sourcePath: "content/docs/sage-content-engineering.md",
      title: "SAGE Content Engineering",
      description: "How Shyena researches, verifies, drafts, reviews, and publishes technical content through an evidence-aware content engineering pipeline.",
      slug: "sage-content-engineering",
      category: "Content Engineering",
      primary_keyword: "AI content engineering",
      search_intent: "informational",
      author: "Shyena Engineering",
      published: "true",
    },
  ],
} as const;
