import { existsSync, mkdirSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join, relative } from "node:path";

const ROOT = process.cwd();
const contentRoot = join(ROOT, "content");
const generatedDir = join(ROOT, "src", "content");
const output = join(generatedDir, "generated-content.ts");

// Keep the generated registry limited to publishable content. SAGE research,
// review, evidence, SEO, and repository README artifacts are not application pages.
function isPublishableMarkdown(name) {
  return name.endsWith(".md") && name !== "README.md" && !/\.(research|review)\.md$/i.test(name);
}

function parseFrontmatter(source) {
  if (!source.startsWith("---\n")) return {};
  const end = source.indexOf("\n---", 4);
  if (end === -1) throw new Error("Missing frontmatter terminator");

  const result = {};
  for (const line of source.slice(4, end).split("\n")) {
    const match = line.match(/^([A-Za-z0-9_-]+):\s*(.*)$/);
    if (!match) continue;
    const [, key, raw] = match;
    const value = raw.trim().replace(/^['"]|['"]$/g, "");
    result[key] = value;
  }
  return result;
}

function walk(dir, files = []) {
  if (!existsSync(dir)) return files;
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const full = join(dir, entry.name);
    if (entry.isDirectory()) walk(full, files);
    else if (isPublishableMarkdown(entry.name)) files.push(full);
  }
  return files;
}

function loadContent(type, dir) {
  return walk(dir).map((file) => {
    const source = readFileSync(file, "utf8");
    const meta = parseFrontmatter(source);
    if (!meta.title || !meta.slug || !meta.description) {
      throw new Error(`Invalid content frontmatter: ${relative(ROOT, file)}`);
    }
    return {
      type,
      sourcePath: relative(ROOT, file).replaceAll("\\", "/"),
      ...meta,
    };
  });
}

const articles = loadContent("blog", join(contentRoot, "blog"));
const docs = loadContent("docs", join(contentRoot, "docs"));

mkdirSync(generatedDir, { recursive: true });

const source = `// AUTO-GENERATED by scripts/generate-content.mjs. Do not edit manually.\n\nexport type GeneratedContentMeta = {\n  type: \"blog\" | \"docs\";\n  sourcePath: string;\n  title: string;\n  slug: string;\n  description: string;\n  category?: string;\n  primary_keyword?: string;\n  search_intent?: string;\n  author?: string;\n  published?: string;\n};\n\nexport const generatedContent = ${JSON.stringify({ articles, docs }, null, 2)} as const;\n`;

writeFileSync(output, source);
console.log(`Generated ${articles.length} blog articles and ${docs.length} docs entries.`);
