import type { ReactNode } from "react";

export type ArticleConcept = "systems" | "trajectory" | "false-pass" | "cognigy" | "security" | "judge" | "tokenomics";
type Node = { x: number; y: number; label: string; sub?: string; tone?: "gold" | "purple" | "muted" | "danger" };
type Edge = { from: number; to: number; danger?: boolean; dashed?: boolean };
const palette = { gold: "#d99a00", purple: "#7c3aed", muted: "#64748b", danger: "#dc2626" };

function Frame({ title, eyebrow, children }: { title: string; eyebrow: string; children: ReactNode }) {
  return <figure className="shyena-concept-figure" aria-label={title}>
    <div className="shyena-concept-header"><span>{eyebrow}</span><strong>{title}</strong></div>
    <svg viewBox="0 0 1200 430" role="img" aria-labelledby="article-concept-title" className="shyena-concept-svg">
      <title id="article-concept-title">{title}</title>
      <defs>
        <pattern id="concept-grid" width="48" height="48" patternUnits="userSpaceOnUse"><path d="M 48 0 L 0 0 0 48" fill="none" stroke="#e2e8f0" strokeWidth="1" /></pattern>
        <marker id="concept-arrow" markerWidth="8" markerHeight="8" refX="7" refY="4" orient="auto"><path d="M0,0 L8,4 L0,8 Z" fill="#94a3b8" /></marker>
        <marker id="concept-arrow-danger" markerWidth="8" markerHeight="8" refX="7" refY="4" orient="auto"><path d="M0,0 L8,4 L0,8 Z" fill={palette.danger} /></marker>
      </defs>
      <rect width="1200" height="430" fill="#fffdf8" /><rect width="1200" height="430" fill="url(#concept-grid)" opacity=".62" />{children}
    </svg>
  </figure>;
}
function NodeBox({ node }: { node: Node }) {
  const stroke = palette[node.tone || "muted"];
  const fill = node.tone === "gold" ? "#fff8df" : node.tone === "danger" ? "#fff5f5" : "#ffffff";
  return <g><rect x={node.x - 78} y={node.y - 34} width="156" height="68" rx="12" fill={fill} stroke={stroke} strokeWidth="1.8" /><text x={node.x} y={node.y - 2} textAnchor="middle" fill="#0f172a" fontFamily="Inter,ui-sans-serif,system-ui" fontSize="14" fontWeight="700">{node.label}</text>{node.sub && <text x={node.x} y={node.y + 18} textAnchor="middle" fill="#64748b" fontFamily="Inter,ui-sans-serif,system-ui" fontSize="10.5">{node.sub}</text>}</g>;
}
function EdgeLines({ nodes, edges }: { nodes: Node[]; edges: Edge[] }) {
  return <g fill="none" strokeLinecap="round">{edges.map((edge, i) => { const a = nodes[edge.from], b = nodes[edge.to]; if (!a || !b) return null; const horizontal = Math.abs(b.x-a.x) >= Math.abs(b.y-a.y); const x1 = horizontal ? a.x + (b.x>a.x?78:-78) : a.x; const y1 = horizontal ? a.y : a.y + (b.y>a.y?34:-34); const x2 = horizontal ? b.x + (b.x>a.x?-78:78) : b.x; const y2 = horizontal ? b.y : b.y + (b.y>a.y?-34:34); return <line key={i} x1={x1} y1={y1} x2={x2} y2={y2} stroke={edge.danger?palette.danger:"#94a3b8"} strokeWidth={edge.danger?2.4:1.6} strokeDasharray={edge.dashed?"6 6":undefined} markerEnd={edge.danger?"url(#concept-arrow-danger)":"url(#concept-arrow)"} />; })}</g>;
}
function Diagram({ title, eyebrow, nodes, edges, caption }: { title: string; eyebrow: string; nodes: Node[]; edges: Edge[]; caption: string }) {
  return <Frame title={title} eyebrow={eyebrow}><EdgeLines nodes={nodes} edges={edges} />{nodes.map(n=><NodeBox key={`${n.x}-${n.y}`} node={n}/>)}<text x="600" y="405" textAnchor="middle" fill="#475569" fontFamily="JetBrains Mono,ui-monospace,monospace" fontSize="12" fontWeight="600">{caption}</text></Frame>;
}
function SystemsDiagram(){const nodes:Node[]=[{x:600,y:76,label:"AI AGENT",sub:"system under assurance",tone:"gold"},{x:160,y:210,label:"GOAL",sub:"user outcome",tone:"purple"},{x:410,y:210,label:"ORCHESTRATION",sub:"route · intent · handoff",tone:"purple"},{x:665,y:210,label:"TOOLS",sub:"actions · side effects",tone:"purple"},{x:1040,y:210,label:"SECURITY",sub:"boundaries · abuse",tone:"danger"},{x:300,y:350,label:"DETERMINISTIC",sub:"contracts · facts"},{x:600,y:350,label:"GENERATED ANSWERS",sub:"quality · grounding",tone:"gold"},{x:900,y:350,label:"EVIDENCE",sub:"trace · outcome · proof",tone:"gold"}];return <Diagram title="AI agent testing as a systems problem" eyebrow="SYSTEM VIEW" nodes={nodes} edges={[{from:0,to:1},{from:0,to:2},{from:0,to:3},{from:0,to:4},{from:1,to:5},{from:2,to:5},{from:2,to:6},{from:3,to:6},{from:4,to:7},{from:5,to:7},{from:6,to:7}]} caption="MULTIPLE SIGNALS → ONE EVIDENCE CHAIN → RELEASE VERDICT"/>;}
function TrajectoryDiagram(){const nodes:Node[]=[{x:120,y:215,label:"PERSONA",sub:"same intent",tone:"gold"},{x:360,y:130,label:"PATH A",sub:"valid route",tone:"purple"},{x:360,y:300,label:"PATH B",sub:"valid route",tone:"purple"},{x:650,y:130,label:"PATH C",sub:"valid route",tone:"purple"},{x:650,y:300,label:"PATH D",sub:"valid route",tone:"purple"},{x:940,y:215,label:"GOAL",sub:"same outcome",tone:"gold"}];return <Diagram title="One goal can have multiple valid trajectories" eyebrow="TRAJECTORY VIEW" nodes={nodes} edges={[{from:0,to:1},{from:0,to:2},{from:1,to:3},{from:2,to:4},{from:3,to:5},{from:4,to:5}]} caption="TEST THE GOAL AND ACCEPTABLE TRAJECTORIES — NOT ONE SCRIPT"/>;}
function FalsePassDiagram(){const nodes:Node[]=[{x:140,y:215,label:"START",sub:"planned journey"},{x:390,y:215,label:"TURN 1–6",sub:"quality = 0.81",tone:"gold"},{x:640,y:215,label:"TRUNCATED",sub:"timeout / error",tone:"danger"},{x:900,y:125,label:"QUALITY SCORE",sub:"looks green",tone:"gold"},{x:900,y:305,label:"INTEGRITY GATE",sub:"BLOCK",tone:"danger"}];return <Diagram title="A quality score cannot rescue a broken execution" eyebrow="FALSE-PASS CONTROL" nodes={nodes} edges={[{from:0,to:1},{from:1,to:2,danger:true},{from:2,to:3,dashed:true},{from:2,to:4,danger:true}]} caption="EXECUTION INTEGRITY FIRST → QUALITY SCORE CANNOT HIDE FAILURE"/>;}
function CognigyDiagram(){const nodes:Node[]=[{x:120,y:215,label:"COGNIGY FLOW",sub:"structure",tone:"purple"},{x:350,y:215,label:"JOURNEY",sub:"goal · persona",tone:"gold"},{x:580,y:215,label:"LIVE SESSION",sub:"chat / voice",tone:"purple"},{x:790,y:125,label:"DETERMINISTIC",sub:"contracts"},{x:790,y:305,label:"SEMANTIC",sub:"quality + meaning",tone:"gold"},{x:1030,y:215,label:"EVIDENCE",sub:"verdict + trace",tone:"gold"}];return <Diagram title="From Cognigy flow to assurance evidence" eyebrow="COGNIGY ASSURANCE" nodes={nodes} edges={[{from:0,to:1},{from:1,to:2},{from:2,to:3},{from:2,to:4},{from:3,to:5},{from:4,to:5}]} caption="FLOW → JOURNEY → EXECUTION → EVALUATION → EVIDENCE"/>;}
function SecurityDiagram(){const nodes:Node[]=[{x:120,y:215,label:"CHANGE",sub:"agent surface",tone:"gold"},{x:340,y:120,label:"THREAT MODEL",sub:"exposure",tone:"purple"},{x:340,y:310,label:"SYSTEM GRAPH",sub:"flows + tools",tone:"purple"},{x:570,y:215,label:"HYPOTHESES",sub:"attack paths",tone:"purple"},{x:790,y:215,label:"RISK / COST",sub:"prioritize",tone:"gold"},{x:1000,y:120,label:"ZIRAN",sub:"adaptive attack",tone:"danger"},{x:1000,y:310,label:"VERDICT",sub:"evidence",tone:"danger"}];return <Diagram title="Security testing starts with risk, not random attacks" eyebrow="SECURITY ASSURANCE" nodes={nodes} edges={[{from:0,to:1},{from:0,to:2},{from:1,to:3},{from:2,to:3},{from:3,to:4},{from:4,to:5},{from:5,to:6,danger:true},{from:4,to:6,danger:true,dashed:true}]} caption="MODEL → PRIORITIZE → ATTACK → VERIFY → GOVERN"/>;}
function JudgeDiagram(){const nodes:Node[]=[{x:130,y:215,label:"TRANSCRIPT",sub:"observable run"},{x:360,y:215,label:"RUBRIC",sub:"quality dimensions",tone:"gold"},{x:600,y:125,label:"GROUNDING",sub:"evidence",tone:"purple"},{x:600,y:305,label:"RELEVANCE",sub:"task fit",tone:"purple"},{x:840,y:215,label:"JUDGE",sub:"score + reasoning",tone:"gold"},{x:1050,y:215,label:"EVIDENCE",sub:"traceable result",tone:"gold"}];return <Diagram title="LLM-as-judge is a reasoned evaluation layer" eyebrow="SEMANTIC EVALUATION" nodes={nodes} edges={[{from:0,to:1},{from:1,to:2},{from:1,to:3},{from:2,to:4},{from:3,to:4},{from:4,to:5}]} caption="RUBRIC + CONTEXT + REASONING → TRACEABLE JUDGMENT"/>;}
function TokenomicsDiagram(){const nodes:Node[]=[{x:130,y:215,label:"TOKENS",sub:"execution cost",tone:"gold"},{x:350,y:215,label:"BEHAVIOUR",sub:"what happened",tone:"purple"},{x:570,y:215,label:"ASSURANCE",sub:"trust + controls",tone:"purple"},{x:790,y:215,label:"VALUE",sub:"business outcome",tone:"gold"},{x:1010,y:215,label:"IMPACT",sub:"strategic result",tone:"gold"}];return <Diagram title="Assurance economics connects execution to business impact" eyebrow="ASSURANCE ECONOMICS" nodes={nodes} edges={[{from:0,to:1},{from:1,to:2},{from:2,to:3},{from:3,to:4}]} caption="COST → BEHAVIOUR → ASSURANCE → VALUE → IMPACT"/>;}
export function ArticleConceptDiagram({concept}:{concept:ArticleConcept}){switch(concept){case"trajectory":return <TrajectoryDiagram/>;case"false-pass":return <FalsePassDiagram/>;case"cognigy":return <CognigyDiagram/>;case"security":return <SecurityDiagram/>;case"judge":return <JudgeDiagram/>;case"tokenomics":return <TokenomicsDiagram/>;default:return <SystemsDiagram/>;}}
