/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ChakraRouteImport } from './routes/chakra'
import { Route as CisRouteImport } from './routes/cis'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as NexusRouteImport } from './routes/nexus'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as ProductRouteImport } from './routes/product'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as VeraRouteImport } from './routes/vera'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as DocsEvaluationModelRouteImport } from './routes/docs.evaluation-model'
import { Route as DocsGettingStartedRouteImport } from './routes/docs.getting-started'
import { Route as DocsReportingRouteImport } from './routes/docs.reporting'
import { Route as DocsTroubleshootingRouteImport } from './routes/docs.troubleshooting'
import { Route as DocsWritingTestSpecsRouteImport } from './routes/docs.writing-test-specs'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ChakraRoute = ChakraRouteImport.update({
  id: '/chakra',
  path: '/chakra',
  getParentRoute: () => rootRouteImport,
} as any)
const CisRoute = CisRouteImport.update({
  id: '/cis',
  path: '/cis',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const NexusRoute = NexusRouteImport.update({
  id: '/nexus',
  path: '/nexus',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductRoute = ProductRouteImport.update({
  id: '/product',
  path: '/product',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const VeraRoute = VeraRouteImport.update({
  id: '/vera',
  path: '/vera',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsEvaluationModelRoute = DocsEvaluationModelRouteImport.update({
  id: '/evaluation-model',
  path: '/evaluation-model',
  getParentRoute: () => DocsRoute,
} as any)
const DocsGettingStartedRoute = DocsGettingStartedRouteImport.update({
  id: '/getting-started',
  path: '/getting-started',
  getParentRoute: () => DocsRoute,
} as any)
const DocsReportingRoute = DocsReportingRouteImport.update({
  id: '/reporting',
  path: '/reporting',
  getParentRoute: () => DocsRoute,
} as any)
const DocsTroubleshootingRoute = DocsTroubleshootingRouteImport.update({
  id: '/troubleshooting',
  path: '/troubleshooting',
  getParentRoute: () => DocsRoute,
} as any)
const DocsWritingTestSpecsRoute = DocsWritingTestSpecsRouteImport.update({
  id: '/writing-test-specs',
  path: '/writing-test-specs',
  getParentRoute: () => DocsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/chakra': typeof ChakraRoute
  '/cis': typeof CisRoute
  '/contact': typeof ContactRoute
  '/docs': typeof DocsRouteWithChildren
  '/nexus': typeof NexusRoute
  '/pricing': typeof PricingRoute
  '/product': typeof ProductRoute
  '/security': typeof SecurityRoute
  '/services': typeof ServicesRoute
  '/vera': typeof VeraRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/docs/evaluation-model': typeof DocsEvaluationModelRoute
  '/docs/getting-started': typeof DocsGettingStartedRoute
  '/docs/reporting': typeof DocsReportingRoute
  '/docs/troubleshooting': typeof DocsTroubleshootingRoute
  '/docs/writing-test-specs': typeof DocsWritingTestSpecsRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/chakra': typeof ChakraRoute
  '/cis': typeof CisRoute
  '/contact': typeof ContactRoute
  '/docs': typeof DocsRouteWithChildren
  '/nexus': typeof NexusRoute
  '/pricing': typeof PricingRoute
  '/product': typeof ProductRoute
  '/security': typeof SecurityRoute
  '/services': typeof ServicesRoute
  '/vera': typeof VeraRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/docs/evaluation-model': typeof DocsEvaluationModelRoute
  '/docs/getting-started': typeof DocsGettingStartedRoute
  '/docs/reporting': typeof DocsReportingRoute
  '/docs/troubleshooting': typeof DocsTroubleshootingRoute
  '/docs/writing-test-specs': typeof DocsWritingTestSpecsRoute
  '/blog': typeof BlogIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/chakra': typeof ChakraRoute
  '/cis': typeof CisRoute
  '/contact': typeof ContactRoute
  '/docs': typeof DocsRouteWithChildren
  '/nexus': typeof NexusRoute
  '/pricing': typeof PricingRoute
  '/product': typeof ProductRoute
  '/security': typeof SecurityRoute
  '/services': typeof ServicesRoute
  '/vera': typeof VeraRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/docs/evaluation-model': typeof DocsEvaluationModelRoute
  '/docs/getting-started': typeof DocsGettingStartedRoute
  '/docs/reporting': typeof DocsReportingRoute
  '/docs/troubleshooting': typeof DocsTroubleshootingRoute
  '/docs/writing-test-specs': typeof DocsWritingTestSpecsRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/chakra'
    | '/cis'
    | '/contact'
    | '/docs'
    | '/nexus'
    | '/pricing'
    | '/product'
    | '/security'
    | '/services'
    | '/vera'
    | '/blog/$slug'
    | '/docs/evaluation-model'
    | '/docs/getting-started'
    | '/docs/reporting'
    | '/docs/troubleshooting'
    | '/docs/writing-test-specs'
    | '/blog/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/chakra'
    | '/cis'
    | '/contact'
    | '/docs'
    | '/nexus'
    | '/pricing'
    | '/product'
    | '/security'
    | '/services'
    | '/vera'
    | '/blog/$slug'
    | '/docs/evaluation-model'
    | '/docs/getting-started'
    | '/docs/reporting'
    | '/docs/troubleshooting'
    | '/docs/writing-test-specs'
    | '/blog'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/chakra'
    | '/cis'
    | '/contact'
    | '/docs'
    | '/nexus'
    | '/pricing'
    | '/product'
    | '/security'
    | '/services'
    | '/vera'
    | '/blog/$slug'
    | '/docs/evaluation-model'
    | '/docs/getting-started'
    | '/docs/reporting'
    | '/docs/troubleshooting'
    | '/docs/writing-test-specs'
    | '/blog/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ChakraRoute: typeof ChakraRoute
  CisRoute: typeof CisRoute
  ContactRoute: typeof ContactRoute
  DocsRoute: typeof DocsRouteWithChildren
  NexusRoute: typeof NexusRoute
  PricingRoute: typeof PricingRoute
  ProductRoute: typeof ProductRoute
  SecurityRoute: typeof SecurityRoute
  ServicesRoute: typeof ServicesRoute
  VeraRoute: typeof VeraRoute
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chakra': {
      id: '/chakra'
      path: '/chakra'
      fullPath: '/chakra'
      preLoaderRoute: typeof ChakraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cis': {
      id: '/cis'
      path: '/cis'
      fullPath: '/cis'
      preLoaderRoute: typeof CisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nexus': {
      id: '/nexus'
      path: '/nexus'
      fullPath: '/nexus'
      preLoaderRoute: typeof NexusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product': {
      id: '/product'
      path: '/product'
      fullPath: '/product'
      preLoaderRoute: typeof ProductRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vera': {
      id: '/vera'
      path: '/vera'
      fullPath: '/vera'
      preLoaderRoute: typeof VeraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/evaluation-model': {
      id: '/docs/evaluation-model'
      path: '/evaluation-model'
      fullPath: '/docs/evaluation-model'
      preLoaderRoute: typeof DocsEvaluationModelRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/getting-started': {
      id: '/docs/getting-started'
      path: '/getting-started'
      fullPath: '/docs/getting-started'
      preLoaderRoute: typeof DocsGettingStartedRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/reporting': {
      id: '/docs/reporting'
      path: '/reporting'
      fullPath: '/docs/reporting'
      preLoaderRoute: typeof DocsReportingRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/troubleshooting': {
      id: '/docs/troubleshooting'
      path: '/troubleshooting'
      fullPath: '/docs/troubleshooting'
      preLoaderRoute: typeof DocsTroubleshootingRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/writing-test-specs': {
      id: '/docs/writing-test-specs'
      path: '/writing-test-specs'
      fullPath: '/docs/writing-test-specs'
      preLoaderRoute: typeof DocsWritingTestSpecsRouteImport
      parentRoute: typeof DocsRoute
    }
  }
}

interface DocsRouteChildren {
  DocsEvaluationModelRoute: typeof DocsEvaluationModelRoute
  DocsGettingStartedRoute: typeof DocsGettingStartedRoute
  DocsReportingRoute: typeof DocsReportingRoute
  DocsTroubleshootingRoute: typeof DocsTroubleshootingRoute
  DocsWritingTestSpecsRoute: typeof DocsWritingTestSpecsRoute
}

const DocsRouteChildren: DocsRouteChildren = {
  DocsEvaluationModelRoute: DocsEvaluationModelRoute,
  DocsGettingStartedRoute: DocsGettingStartedRoute,
  DocsReportingRoute: DocsReportingRoute,
  DocsTroubleshootingRoute: DocsTroubleshootingRoute,
  DocsWritingTestSpecsRoute: DocsWritingTestSpecsRoute,
}

const DocsRouteWithChildren = DocsRoute._addFileChildren(DocsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ChakraRoute: ChakraRoute,
  CisRoute: CisRoute,
  ContactRoute: ContactRoute,
  DocsRoute: DocsRouteWithChildren,
  NexusRoute: NexusRoute,
  PricingRoute: PricingRoute,
  ProductRoute: ProductRoute,
  SecurityRoute: SecurityRoute,
  ServicesRoute: ServicesRoute,
  VeraRoute: VeraRoute,
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
